### ISSUE TITLE
`ern start` command fails

### ISSUE THREAD

**Issue by swashcap** [electrode-io/electrode-native#100]
* **Node.js:** 8.5.0
* **npm:** 4.6.1
* **yarn:** 1.1.0
* **electrode-native:** 1.0.8

(👆 Might be good to put this version stuff in the issue template.)

* **Problem:** `ern start` exits with a JavaScript error:
    ```shell
    $ ern start
    ___ _        _               _       _  _      _   _         
    | __| |___ __| |_ _ _ ___  __| |___  | \| |__ _| |_(_)_ _____ 
    | _|| / -_) _|  _| '_/ _ \/ _` / -_) | .` / _` |  _| \ V / -_)
    |___|_\___\__|\__|_| \___/\__,_\___| |_|\_\__,_|\__|_|\_/\___|
    [v0.7.0] [Cauldron: -NONE-]

    (0 , _start2.default) is not a function
   ```

   (Something to do with bad `import`?)
* **Expected:** `ern start` should do something, or print a useful error message

**Comment by belemaire** [comment]
electrode-native: 1.0.8 ? ;)

**Comment by belemaire** [comment]
able to reproduce, will look into it

**Comment by swashcap** [comment]
> electrode-native: 1.0.8 ? ;)

Ran this:

```
$ npm ls -g electrode-native
/Users/c0r00jl/.nvm/versions/node/v8.5.0/lib
└── electrode-native@1.0.8  -> /Users/c0r00jl/Projects/electrode-native/global-cli
```

Not sure which package holds the CLI's version!

**Comment by belemaire** [comment]
Oh yes ... that's the global CLI version ;)
Version of the currently activated local CLI is kept in the `.ernrc` file.
`{"platformVersion":"0.7.0" [...]`
We need a `--version` flag ;)
