### ISSUE TITLE
Version command?

### ISSUE THREAD

**Issue by swashcap** [electrode-io/electrode-native#101]
Might be nice for the `ern` CLI to support a `--version` flag that acts like Node.js, npm, etc.: print the version and exit.

**Comment by belemaire** [comment]
Will do.
We have the `ern platform current` command to show the current activated version but it's a bit verbose and not the intuitive / standard way to show current version. `--version` flag is the way indeed.

That being said, version is always display on every command run, so it's easy to see it even by typing `ern`, but i'm sure a lot of people will try `--version` even if its not documented anywhere ;)

For `ern platform current` we don't show the global CLI version, just the local CLI (platform) version.

What we should do is get rid of `ern platform current` and add `--version` flag to `ern` to show both Global CLI and local CLI versions.

**Comment by swashcap** [comment]
Ah, I didn't understand that the `[v0.7.0]` was the current platform version. There's no mention of `current` in `ern --help`, didn't know about it! Neat.
