### ISSUE TITLE
Move global configuration to homedir?

### ISSUE THREAD

**Issue by swashcap** [electrode-io/electrode-native#102]
Noticing the code and [docs](https://github.com/electrode-io/electrode-native/blob/b9b216e6ab56705dc20952ffcd217799d9231c5d/docs/cli/platform/config.md) for the global ern config is at `$HOME/.ern/.ernrc`:

> Get or set the local platform configuration values stored in the `~/.ern/.ernrc` file

Shouldn’t this be in a file at `$HOME/.ernrc` to keep with the expected rc file location of programs?

**Comment by belemaire** [comment]
That's a fair point, but I don't think we'll go down that road as it means that we need to update our global CLI and account for backward compatibility for a few versions of Electrode Native.
It might look odd indeed but I don't see this as a major issue. Maybe the naming of it was not correct, I know of some other tools that keep some local config in the folder itself (though they dont name it rc) for example `.gradle` keeps the global gradle properties there. 
Naming it `rc` was maybe not the right idea :(

**Comment by swashcap** [comment]
It's a minor thing. Perhaps changing the config file's location doesn't require lots of branching in the CLI code: we could simply bump the CLI by a major version to indicate a breaking change, and provide changelog notice and maybe a helpful CLI output if a `~/.ern/.ernrc` is detected.
