### ISSUE TITLE
Communication in between two MiniApps 

### ISSUE THREAD

**Issue by nagender04031989** [electrode-io/electrode-native#1024]
@belemaire - I'm new to electrode native and trying to create the mini apps. Just went through the tutorial for creating MovieListMiniApps which using another miniapp via NavigationAPI. I also created two different miniapps and I want to know the way to connect these two miniapps without Navigation API. Thanks.

**Comment by belemaire** [comment]
Sorry for not giving feedback on this one.
Closing it now as it's been a few months.
Feel free to reopen or create new issue if needed.
