### ISSUE TITLE
AppRegistry error while adding two MiniApps in one container and running in native iOS app in Xcode 10.0

### ISSUE THREAD

**Issue by ankit9495** [electrode-io/electrode-native#1036]
We have trying to combine two miniapps in one container. We succeeded in generating the container and added in our native iOs application. After app launch we get the view of first mini app. But when navigate from one view to other. It opens the second view with the navigation bar as it is shown from the native end. After some delay, it generates the Appregistry error. 
When we searched we get one issue #400 resembled to be same, but no solution is provided. 
Any possible solution to this? Thanks

**Comment by belemaire** [comment]
Sorry for not giving feedback in time on this issue.
Closing it now as it has been a few months without activity.
Feel free to reopen if needed.
