### ISSUE TITLE
Unified code style/linting rules

### ISSUE THREAD

**Issue by swashcap** [electrode-io/electrode-native#104]
What would you think about unifying ESLint rules with [electrode-io/electrode](https://github.com/electrode-io/electrode)? Make not electrode-native core, but the generated `index.[ios|android].js` files and documentation. Would probably make for an easier electrode ↔ electrode-native developer experience. (I _think_ electrode ESLint config is here: https://github.com/walmartlabs/eslint-config-walmart ?)

**Comment by belemaire** [comment]
Yes I think that's a good idea, we'll look into it.

That being said, while I agree that it would make things more aligned internally and also for external developers using this set of rules, I don't think we want to force users into a specific estlint rules set. Might be the default one but in the case we should properly document how to switch to a different set. We could also improve `ern create-miniapp` command to add an option for user to provide an eslint rule set (and use walmart one as default value).

**Comment by belemaire** [comment]
Moving to backlog, in an effort to reduce lingering open issues
