### ISSUE TITLE
Android missing `replaceInFile` directive

### ISSUE THREAD

**Issue by davidgovea** [electrode-io/electrode-native#1060]
`replaceInFile` is [listed as a platform-independent directive](https://native.electrode.io/reference/index-2/native-modules#platform-agnostic-directives), but it looks like it's not implemented on Android.

I'm working on a manifest entry for a more involved RN module: `react-native-gesture-handler`, which needs edits to the `ReactActivityDelegate` class definition (https://kmagiera.github.io/react-native-gesture-handler/docs/getting-started.html).

File replacement is not necessarily the best way to do this, but it is a very powerful directive that unlocks a lot of possibilities.

I have an initial implementation here: https://github.com/electrode-io/electrode-native/compare/master...runtrizapps:feature/android-replace-in-file?expand=1

---

Worth noting: I'm performing the replacements *after* the mustache templates are evaluated, which may differ from the approach on iOS (it seems like `replaceInFile` is designed to process incoming plugin files, not the final container files).

Perhaps a container transformer would be more appropriate? Not sure if there is a way to link a manifest-plugin entry with a container transformation..

Not submitting a PR at this time: just want to hear thoughts/rationale from the team. Happy to refactor or try out different approaches.

Thank you!

**Comment by deepueg** [comment]
@davidgovea Thanks for opening this issue and providing suggestions. We will have a discussion around this to consider various options and let you the path forward. Thanks again.

**Comment by davidgovea** [comment]
Live in `v0.34.0`, thank you!
