### ISSUE TITLE
addStaticLibrary option in pbxproj adds invalid path for LIBRARY_SEARCH_PATHS

### ISSUE THREAD

**Issue by georgeloring** [electrode-io/electrode-native#1065]
Plugin configuration for iOS has this entry:

```
     "pbxproj": {
        "addStaticLibrary": [
           "{{{projectName}}}/Libraries/libAppAuth.a"
        ],
```

Library is added to project, but the LIBRARY_SEARCH_PATHS entry that is added for the library has 'undefined' in the path:

```
LIBRARY_SEARCH_PATHS = (
                                        "$(inherited)",
                                        "\"$(SRCROOT)/undefined/ElectrodeContainer/Libraries\""
);
```

**Comment by belemaire** [comment]
Fixed by https://github.com/belemaire/xcode-ern/commit/19604a671441a9d1da33537498dce972f2fc92d4

Will be shipped with Electrode Native 0.30.0
