### ISSUE TITLE
Add support for git@github.com:${USER}/${REPO}#${BRANCH} for the 'add miniapps' command

### ISSUE THREAD

**Issue by LuisRizo** [electrode-io/electrode-native#1074]
I was easily able to run `ern cauldron repo add <alias> <ssh_git_url>`. But this is currently impossible when using the command `ern cauldron add miniapps <ssh_git_url_with_branch>`.

I get the following error:
`
✖ An error occurred: Unsupported version github.com:user/repo.git#branch for git
`

The ideal solution would be to have the same behavior on the `cauldron miniapps` fraction of the CLI as the one in `cauldron repo` regarding the git urls allowed

**Comment by belemaire** [comment]
Hi @LuisRizo,

Electrode Native supports adding MiniApps from git repo, either using `https` or `ssh` url scheme.
Or documentation does not seems fully up to date on this matter, I will update it.
Internally, our Cauldrons are using git ssh based MiniApps, so I can confirm that this works fine ;)

That being said, the MiniApps ssh url that you provide to the `ern cauldron add miniapps` command should be formatted as follow :

`git+ssh://git@${}/${ORG_OR_USER}/${REPO}.git#${BRANCH}`

For example for master branch of MiniApp repository on `github.com` named `MyMiniApp` in org `MyOrg`, the url would be

`git+ssh://git@github.com/MyOrg/MyMiniApp.git#master`

I would also highly recommend using a version of Electrode Native >= 0.28 to get proper complete support of git based MiniApps.

**Comment by LuisRizo** [comment]
Hey @belemaire,

Thank you for the quick response.

After manually changing the regex to accept my proposed MiniApp Github URL, I encountered many problems so I realized it was not as easy as I thought.

However, I also realized that I was using the pattern you just mentioned wrong

I was using: 
`git+ssh://git@${GIT_HOST}:${ORG_OR_USER}/${REPO}.git#${BRANCH}`
Instead of
`git+ssh://git@${GIT_HOST}/${ORG_OR_USER}/${REPO}.git#${BRANCH}`

After the `GIT_HOST`, I was using `:` instead of the appropriate `/`. After realizing this I was able to add the MiniApp successfully.

Thank you for your help!
