### ISSUE TITLE
Auto increment container version not working with cauldron update

### ISSUE THREAD

**Issue by devpascoe** [electrode-io/electrode-native#1090]
New the the platform. Using latest bits.
I have a cauldron set up, mini app and native app. Container added and all private repos sitting in bitbucket.

If i ern cauldron regen-container it will create the output in the container repo. And set "containerVersion": "1.0.0" within the cauldron > platform eg ios
It doesn't store it in config > containerGenerator as it would appear its looking for in [this commit](https://github.com/electrode-io/electrode-native/commit/785bd1ae083ad335ae0f86fab5be4f1c865fd4ca)

I can specify a --containerVersion but i'd like things to autoincrement if possible.

My understanding is:
1. mini app is updated with new code.
2. [optionally] tag mini app's latest commit if you want to code push, then code push that tag
3. ern cauldron update miniapps https://myusername@bitbucket.org/accountname/miniappname.git#master --descriptor MyApp:ios:0.0.4

This should trigger a new container to be built with latest miniapp js code bundled. But instead i get errors like this
`✖ [performContainerStateUpdateInCauldron] An error occurred: Error: fatal: tag 'v1.0.0-raw' already e
xists
✖ 
✖ An error occurred: fatal: tag 'v1.0.0-raw' already exists`

**Comment by devpascoe** [comment]
Should it auto increment container version?

**Comment by belemaire** [comment]
@devpascoe 
It should auto increment the container version, if no explicit version is specified, otherwise this is a bug. Could you provide your current `cauldron.json` file as a gist for us to look into if possible ?

Now I'm not sure for this point

```
ern cauldron update miniapps https://myusername@bitbucket.org/accountname/miniappname.git#master --descriptor MyApp:ios:0.0.4
```

you shouldn't need to do `update miniapps` with branches. unless you are updating the branch of the miniapp (for ex it was using `foo` branch and is now using `master` branch).

`update miniapps` is only used if you need to update (change) the `branch` of a miniapp or update the version of a miniapp (if using npm published versions or tagged git versions -not common-).

If you added your miniapps as git branches, you just need to run the `ern cauldron regen-container`. This command will pull the latest from all branches and regenerate a new container containing all the changes from all miniapps.

**Comment by belemaire** [comment]
Closing this one now, feel free to reopen if needed.

**Comment by devpascoe** [comment]
Finally had a moment to revisit this, sorry its been so long. I'm still trying to understand the flow.
So, fresh project.
```
ern create-miniapp myprojectMiniApp
ern cauldron repo add .....
ern cauldron add nativeapp myapp:ios:0.0.1
ern cauldron add miniapps https://myusername@bitbucket.org/myrepo/myprojectMiniApp.git#master
ern create-container --descriptor myapp:ios:0.0.1
ern publish-container --platform ios --publisher ern-container-publisher-git --url https://myusername@bitbucket.org/myrepo/myapp-ios-container.git
```
I see my container repo tagged v1.0.0 on latest commit. carthage update working and miniapp initialized.

So i want to make a code change in my mini app. git commit changes to master in my miniapp repo.
I run the following to ensure my cauldron.json tracks latest commit on the miniapp repo:
```ern cauldron regen-container```
Then i publish the container hoping it will auto-increment:
```ern publish-container --platform ios --publisher ern-container-publisher-git --url https://myusername@bitbucket.org/myrepo/myapp-ios-container.git```
However i get: "An error occurred: fatal: tag 'v1.0.0' already exists".
```
{
  "name": "Cauldron",
  "nativeApps": [
    {
      "name": "myapp",
      "platforms": [
        {
          "name": "ios",
          "versions": [
            {
              "name": "0.0.1",
              "binary": null,
              "codePush": {},
              "container": {
                "jsApiImpls": [],
                "miniApps": [
                  "https://myusername@bitbucket.org/myreop/myprojectMiniApp.git#10d49fe6e911db8323d11e0f72c388bbd2f57213"
                ],
                "nativeDeps": [
                  "ernnavigation-api-impl-native@1.3.20",
                  "ernnavigation-api@1.2.5",
                  "react-native-electrode-bridge@1.5.23",
                  "react-native@0.60.5"
                ],
                "miniAppsBranches": [
                  "https://myusername@bitbucket.org/myrepo/myprojectMiniApp.git#master"
                ],
                "ernVersion": "0.38.15"
              },
              "isReleased": false,
              "nativeDeps": [],
              "yarnLocks": {
                "container": "17759fd1-41ea-46ad-8f44-af7d61b53cff"
              },
              "containerVersion": "1.0.0"
            }
          ]
        }
      ]
    }
  ],
  "schemaVersion": "3.0.0"
}
```
Note: i can specify ```--version``` on the publish-container command eg, 1.0.1 but was hoping to autoincrement the container.
Finally, i have also tried adding a new nativeapp version 1.0.2 and it yielded the same result of "v1.0.0 already exists".
