### ISSUE TITLE
Code-Push commands are showing less descriptors than are in the cauldron

### ISSUE THREAD

**Issue by LuisRizo** [electrode-io/electrode-native#1093]
I created an `Awesome` native-app, an `AwesomeMiniApp` miniapp, and `awesome-cauldron` cauldron.

Here is the cauldron.json: https://gist.github.com/LuisRizo/86c73b6f81326f76473b11232a4c8ba0

There I have the following nativeapp descriptors:
- `Awesome:ios:0.0.1`
- `Awesome:ios:1.0.0`

All the Github repositories are private but I have no problem making them public if it helps you debug this issue

I used the following command to code-push and it worked beautifully (great job on this btw! 💯):

```
 luisrizo@Luis-Rizo-MacBook-Pro  ~/Projects/AwesomeMiniApp   master  ern code-push release --miniapps git+ssh://git@github.com/LuisRizo/AwesomeMiniApp.git#v1.0.3 --description="First Code-Push" -d Awesome:ios:1.0.0 -m  -s
/Users/luisrizo/.ern/.ernrc
 ___ _        _               _       _  _      _   _         
| __| |___ __| |_ _ _ ___  __| |___  | \| |__ _| |_(_)_ _____ 
| _|| / -_) _|  _| '_/ _ \/ _` / -_) | .` / _` |  _| \ V / -_)
|___|_\___\__|\__|_| \___/\__,_\___| |_|\_\__,_|\__|_|\_/\___|
[v0.29.6] [Cauldron: Awesome-cauldron]
✔ Ensuring that preconditions for code-push command are valid 0s
✔ Ensuring that preconditions for code-push command are valid 0s
✔ Ensuring that native application descriptor exists in Cauldron 0s
✔ Ensuring that all descriptors are for the same native application and platform 0s
✔ Ensuring that no file system path(s) is/are used 0s
✔ Checking native dependencies version alignment of git+ssh://git@github.com/LuisRizo/AwesomeMiniApp.git#v1.0.3 with Awesome:ios:1.0.0 10s
✔ Checking compatibility 0s
ℹ Awesome:ios:1.0.0 : COMPATIBLE
ℹ ┌────────────────────────────────────────┬────────────────┬───────────────┐
ℹ │ Name                                   │ Needed Version │ Local Version │
ℹ ├────────────────────────────────────────┼────────────────┼───────────────┤
ℹ │ react-native                           │ 0.57.8         │ 0.57.8        │
ℹ ├────────────────────────────────────────┼────────────────┼───────────────┤
ℹ │ react-native-code-push                 │ 5.4.2          │ 5.4.2         │
ℹ └────────────────────────────────────────┴────────────────┴───────────────┘
ℹ git+ssh://git@github.com/LuisRizo/AwesomeMiniApp.git#v1.0.3 native dependencies versions are aligned with Awesome:ios:1.0.0
✔ Generating composite module 9s
✔ Generating composite bundle for miniapps 5s
ℹ Target Binary version : 1.0.0
✔ Releasing bundle through CodePush 2s
✔ Adding yarn.lock to Cauldron 0s
ℹ Successfully released
```

However, I wanted to try disabling the last code-push version through the CLI targeted at `Awesome:ios:1.0.0` and I wasn't able to do it because it only suggested me the `Awesome:ios:0.0.1` descriptor.

```
 luisrizo@Luis-Rizo-MacBook-Pro  ~/Projects/AwesomeMiniApp   master  ern code-push patch --disabled true --des Awesome:ios:1.0.0/Users/luisrizo/.ern/.ernrc
 ___ _        _               _       _  _      _   _         
| __| |___ __| |_ _ _ ___  __| |___  | \| |__ _| |_(_)_ _____ 
| _|| / -_) _|  _| '_/ _ \/ _` / -_) | .` / _` |  _| \ V / -_)
|___|_\___\__|\__|_| \___/\__,_\___| |_|\_\__,_|\__|_|\_/\___|
[v0.29.9] [Cauldron: Awesome-cauldron]

? Choose a native application version (Use arrow keys)
❯ Awesome:ios:0.0.1 
```

I tried passing the `--des` flag as mentioned in the docs for [`patch`](https://native.electrode.io/cli-commands/code-push/patch) but that didn't do anything. I was still asked to pick a single native application.

The docs on the CLI for patch do not include the `--des` flag, so I assume the docs on the website are outdated.

This is the output of doing `ern cauldron get nativeapp`

```
 ✘ luisrizo@Luis-Rizo-MacBook-Pro  ~/Projects/AwesomeMiniApp   master  ern cauldron get nativeapp                                 
/Users/luisrizo/.ern/.ernrc
 ___ _        _               _       _  _      _   _         
| __| |___ __| |_ _ _ ___  __| |___  | \| |__ _| |_(_)_ _____ 
| _|| / -_) _|  _| '_/ _ \/ _` / -_) | .` / _` |  _| \ V / -_)
|___|_\___\__|\__|_| \___/\__,_\___| |_|\_\__,_|\__|_|\_/\___|
[v0.29.9] [Cauldron: Awesome-cauldron]

ℹ Awesome:ios:0.0.1
ℹ Awesome:ios:1.0.0
```

I also tried doing a code-push release without the `descriptor` as the CLI argument and I was only prompted with one nativeapp version

```
 luisrizo@Luis-Rizo-MacBook-Pro  ~/Projects/AwesomeMiniApp   master  ern code-push release --miniapps git+ssh://git@github.com/LuisRizo/AwesomeMiniApp.git#v1.0.3 --description="First Code-Push" -m  -s
/Users/luisrizo/.ern/.ernrc
 ___ _        _               _       _  _      _   _         
| __| |___ __| |_ _ _ ___  __| |___  | \| |__ _| |_(_)_ _____ 
| _|| / -_) _|  _| '_/ _ \/ _` / -_) | .` / _` |  _| \ V / -_)
|___|_\___\__|\__|_| \___/\__,_\___| |_|\_\__,_|\__|_|\_/\___|
[v0.29.9] [Cauldron: Awesome-cauldron]

✔ Ensuring that preconditions for code-push command are valid 0s
? Choose a native application version (Press <space> to select, <a> to toggle all, <i> to inverse selection)
❯◯ Awesome:ios:0.0.1
```

Other commands like `ern cauldron add miniapps` shows only one descriptor as well, but this one is the last version of it (1.0.0, instead of 0.0.1)

```
 luisrizo@Luis-Rizo-MacBook-Pro  ~/Projects/AwesomeMiniApp   master  ern cauldron add miniapps  git+ssh://git@github.com/LuisRizo/AwesomeMiniApp.git#master 
/Users/luisrizo/.ern/.ernrc
 ___ _        _               _       _  _      _   _         
| __| |___ __| |_ _ _ ___  __| |___  | \| |__ _| |_(_)_ _____ 
| _|| / -_) _|  _| '_/ _ \/ _` / -_) | .` / _` |  _| \ V / -_)
|___|_\___\__|\__|_| \___/\__,_\___| |_|\_\__,_|\__|_|\_/\___|
[v0.29.9] [Cauldron: Awesome-cauldron]

? Choose a native application version (Use arrow keys)
❯ Awesome:ios:1.0.0 
```

I want to believe that in order to fix this issue, the helper function that is used to suggest Nativeapps on `code-push` related commands should be updated or replaced with one that works like `cauldron` commands. Also adding the option to pass a `descriptor` to the `patch` command would be nice

**Comment by belemaire** [comment]
Hi @LuisRizo 
Sorry for the slight delay, our team was attending an offsite and we had very limited availability.
Quite a few questions here, I'll handle them one by one 

```
 I wanted to try disabling the last code-push version through the CLI targeted at Awesome:ios:1.0.0 and I wasn't able to do it because it only suggested me the Awesome:ios:0.0.1 descriptor
```

For any `ern code-push` command, Electrode Native will only list native application versions from the Cauldron that are flagged as being released (i.e `"isReleased": true` in the Cauldron). Because only `0.0.1` is flagged as released in your Cauldron, it only lists this one. This is because you might end up having a lot of versions in your Cauldron, and it does not really make sense to use CodePush if your version is not released (as it's still possible to generate a Container in that case). For convenience we therefore only list released versions. 

To bypass this 'restriction' you can just pass the descriptor (native app version) manually on the command line, by using the `--descriptor` option of the command (`--descriptor Awesome:ios:1.0.0`)

I can see that you mentioned trying it 

```
I tried passing the --des flag as mentioned in the docs for patch but that didn't do anything. I was still asked to pick a single native application.
The docs on the CLI for patch do not include the --des flag, so I assume the docs on the website are outdated
```

The thing here, is that you didn't used the right option. You use `--des` instead of `--descriptor`.
`--des` is an alias for `--description`, which is an arbitrary string describing what this code push update is about (totally optional).

FYI, even if doc is outdated, for every command you can use `--help` to list the options (for ex `ern code-push patch --help`), this would have listed you the difference here :

```
-description, --des  Description of the changes made to the app with this release
--descriptor              Full native application descriptor from which to promote a release
```

Will update documentation as it seems indeed is a bit outdated for code-push commands. 
Keeping this issue open, will be closed by pull request containing documentation update.
