### ISSUE TITLE
Android release build issue for real device

### ISSUE THREAD

**Issue by ankit9495** [electrode-io/electrode-native#1117]
Hi @belemaire ,@gmbharath12 

We have developed an android application by using  electrode native. In my application there are 4 mini apps and it is working fine on simulators. But when we are creating a release build for real devices it is working fine when we are installing first time from google drive or any other link.

But after uninstalling and install the release build again from the same location it gives the error **"App not installed"** randomly.

We have tried at our end but not succeeded.Please let us know if you any solution.

Thanks

**Comment by belemaire** [comment]
Hi @ankit9495 
Unfortunately we've not faced or heard of such an issue before.
I don't really see how this problem could come from Electrode Native. Have you tried to search online for such "App not installed" issue on Android ? Sounds like it might come from an issue with the build or device.

**Comment by ankit9495** [comment]
Thanks @belemaire for update.
We have resolve the issue by generating another build for the same.Hence closing the issue.
 If we face this again, will reopen the issue and update you with steps.
