### ISSUE TITLE
fatal: unable to connect to github.com while executing npm install -g electrode-native & ern 

### ISSUE THREAD

**Issue by prabufun** [electrode-io/electrode-native#1126]
Hi ,

i am facing following issue while execute npm install -g electrode-native & ern 

fatal: unable to connect to github.com while executing npm install -g electrode-native & ern 
Exit code: 1
Command: node scripts/postinstall.js
Arguments:
Directory: C:\Users\vn500lt\.ern\versions\0.31.1\node_modules\ern-local-cli
Output:
Cloning electrode-native master manifest
Cloning into 'C:\Users\vn500lt\.ern\ern-master-manifest'...
fatal: unable to connect to github.com:
github.com[0: 192.30.253.113]: errno=No error
github.com[1: 192.30.253.112]: errno=No error

child_process.js:656
    throw err;
    ^

Error: Command failed: git clone https://github.com/electrode-io/electrode-n
e-manifest.git C:\Users\vn500lt\.ern\ern-master-manifest
Cloning into 'C:\Users\vn500lt\.ern\ern-master-manifest'...
fatal: unable to connect to github.com:
github.com[0: 192.30.253.113]: errno=No error
github.com[1: 192.30.253.112]: errno=No error

    at checkExecSyncError (child_process.js:616:11)
    at execSync (child_process.js:653:13)
    at Object.<anonymous> (C:\Users\vn500lt\.ern\versions\0.31.1\node_module
n-local-cli\scripts\postinstall.js:39:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)

info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this
and.

x Something went wrong :( Run the command again with --debug flag for more i

Performing cleanup. Please wait for the process to exit.

could please help me on this.

**Comment by belemaire** [comment]
Looks like your machine is unable to clone the Manifest directory from github due to connection issues with github.com.

Might be a temporary connectivity issue to `github.com` or a more profound problem. 

Are you able to successfully clone a repository from `github.com` on the same machine (just use `git clone` with any remote repository from github.com) ? If not then you should try to figure out why is that the case.

**Comment by belemaire** [comment]
Closing this one. Feel free to reopen if needed.
