### ISSUE TITLE
MiniAppActivity not generated

### ISSUE THREAD

**Issue by tianling536** [electrode-io/electrode-native#1136]
I‘v start up from Building a Movie application demo,throws the follow error while excuting run-android:
~/MovieListMiniApp/android/app/src/main/java/com/walmartlabs/ern/R
unnerConfig.java:10: error: no symbol found
import com.walmartlabs.ern.container.miniapps.MovieListMiniAppActivity;
symbol:   class MovieListMiniAppActivity 

ern version is 0.31.1

**Comment by belemaire** [comment]
@tianling536 
Sorry about that. We were able to reproduce the issue, it was a bug introduced recently.
We released ern version `0.32.2` with the fix.
Thanks for reporting !
