### ISSUE TITLE
how to config annotationProcessor on android native modules

### ISSUE THREAD

**Issue by tianling536** [electrode-io/electrode-native#1137]
Hi,
for example ,config the annotationProcessor "com.github.bumptech.glide:compiler:4.7.1" is not supported.the source code in the AndroidGenerator.ts file only implements regular,files and transitive.

**Comment by belemaire** [comment]
Hi @tianling536 
Yes this is indeed something that is not yet supported through plugin configuration.
Is this native module open sourced, if so could you provide link to github repo ? Would be interested out of curiosity to see their usage of an annotationProcessor. 
We will add support for this in next release, this shouldn't be much.

**Comment by tianling536** [comment]
Thanks for your reply @belemaire 
here's the link, https://github.com/bumptech/glide. 
in fact,this problem happened when i config the 'react-native-fast-image'  plugin,the following complete dependencies config on android:
    implementation("com.github.bumptech.glide:glide:4.7.1") {
        exclude group: "com.android.support", module: "glide"
    }
    implementation("com.github.bumptech.glide:annotations:4.7.1") {
        exclude group: "com.android.support", module: "annotations"
    }
    annotationProcessor "com.github.bumptech.glide:compiler:4.7.1"
    implementation("com.github.bumptech.glide:okhttp3-integration:4.7.1") {
        exclude group: "com.android.support", module: "okhttp3-integration"
        exclude group: "com.android.support", module: "glide-parent"
    }
