### ISSUE TITLE
[Feature] Support `--disable-duplicate-release-error` for CodePush release and promote

### ISSUE THREAD

**Issue by LuisRizo** [electrode-io/electrode-native#1230]
It would be helpful if we were able to forward the `--disable-duplicate-release-error` flag to the CodePush CLI that would allow the `promote` or `release` command to not fail if the same code is attempted to be released.

More info on the feature:
https://docs.microsoft.com/en-us/appcenter/distribution/codepush/cli#no-duplicate-release-error-parameter

**Comment by belemaire** [comment]
Hi @LuisRizo 
Thanks for the suggestion. Makes sense.
It shouldn't be too hard to do, we'll have a look to it and will include this in upcoming `0.35` release.

**Comment by LuisRizo** [comment]
Thank you @belemaire!
