### ISSUE TITLE
Manifest override

### ISSUE THREAD

**Issue by sungmarcus** [electrode-io/electrode-native#1265]
Hi guys,

I am trying to add a new dependency (https://github.com/DoubeBlue/react-native-nfc-hce) by overriding the manifest.
When i try ern add it seems to only be syncing to the main manifest. It gives a plugin not supported error line but still adds it. I presume it is not checking my override manifest at all? Is there a way to check if the manifest is overriding so I can confirm whether or not my cauldron file or the way I added the plugin files is wrong? 

here is my cauldron file:

(I was trying a full override here but have tried partial override which is my main goal)

![Screenshot_20190730_021230](https://user-images.githubusercontent.com/43445027/62093116-eedbb180-b26f-11e9-8607-54ed84bdaaee.png)

Thanks

**Comment by belemaire** [comment]
Hi @sungmarcus 

Not sure which version of Electrode Native you are using, but starting with version `0.32.0` (released a while back, so I think you are on a more recent version), the `config` has been extracted out of the main `cauldron.json` document. I think that may be why `ern` is not processing your config.

See  https://native.electrode.io/reference/index-2/structure#cauldron-configuration-files for some minimal documentation regarding this.

In your case -if and only if you're using a version of ern >= 0.32.0- what you'll need is to create a `config` directory in your Cauldron (if it does not exist yet) and in this directory create a `default.json` file (if it does not exist already), with this content :

```
{
  "manifest": {
    "override": {
        "url": "git@github.com:sungmarcus/electrode-native-manifest.git",
        "type": "partial"
      }
}
```

You should then get rid of the `config` object in your `cauldron.json` file as its useless.

**Comment by sungmarcus** [comment]
Thank you for the response.
I was able to get the override working but now I am approached with a new error.
Any help would be appreciated!
![Screenshot_20190730_152303](https://user-images.githubusercontent.com/43445027/62137561-16696300-b2de-11e9-9abc-929dd22c6b9c.png)

Thanks

**Comment by belemaire** [comment]
Could you run `ern` command you used but with trace log level, by adding  `ERN_LOG_LEVEL=trace` in front of the command. For ex if the command was `ern run-android` with trace log level if would be `ERN_LOG_LEVEL=trace ern run-android`. 
Then paste the last lines of the log leading to this error. 
This will give us more detail about the problem to investigate.

**Comment by sungmarcus** [comment]
So it turns out it was due to a misspelling in my dependencies array in the config.json of the plugin inside the manifest.
How would I implement the following in the config.json?

![Screenshot_20190730_185816](https://user-images.githubusercontent.com/43445027/62154564-dcf51f80-b2fe-11e9-8b2a-8f29e740db50.png)

Thanks

**Comment by sungmarcus** [comment]
I have fixed my problems thank you!
