### ISSUE TITLE
create-miniapp does not work at all.

### ISSUE THREAD

**Issue by AndrewSouthpaw** [electrode-io/electrode-native#1394]
Steps to repo:

1. Run`$ ern create-miniapp fooMiniApp` and choose TypeScript as language. Results in something like the following:

```bash
$ ern create-miniapp fooMiniApp
 ___ _        _               _       _  _      _   _
| __| |___ __| |_ _ _ ___  __| |___  | \| |__ _| |_(_)_ _____
| _|| / -_) _|  _| '_/ _ \/ _` / -_) | .` / _` |  _| \ V / -_)
|___|_\___\__|\__|_| \___/\__,_\___| |_|\_\__,_|\__|_|\_/\___|
[v0.38.7] [Cauldron: -NONE-]

✔ Ensuring that Electrode Native module name is valid 0s
? Input a package name. Press Enter to use the default. foo-miniapp
? Choose the language to use for this MiniApp TypeScript
✔ Ensuring that Electrode Native module name is valid 0s
✔ Ensuring that NPM package name is valid 0s
✖ Creating MiniApp 34s
  ✔ Retrieved react-native version from Manifest [0.60.5] 0s
    ✔ Syncing https://github.com/electrode-io/electrode-native-manifest.git Manifest 0s
  ✖ Creating fooMiniApp project using react-native v0.60.5 33s
✖ An error occurred: ChildProcess exited with code null
```

~Choosing JavaScript seems to avoid the problem.~ UPDATE: even choosing JavaScript, the CLI seems to run forever. (~19 min~ 30 min and counting...)

While there's nothing wrong with adding TypeScript support after the fact using docs from RN (I saw this was referenced in #1254), if the cli doesn't support TypeScript then it shouldn't be an option.

UPDATE: I've tried all the possible combinations (TypeScript + yarn, JavaScript + yarn, JavaScript + npm, etc.) and none of them produce a mini app for me. They hang on

```
  ⠇ Creating SandboxApp project using react-native v0.60.5 ...
```

I let it run for 30 minutes and still nothing.

Env info (omitting some unrelated info):

```
  System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 558.46 MB / 32.00 GB
    Shell: 5.0.7 - /usr/local/bin/bash
  Binaries:
    Node: 8.16.0 - ~/.nvm/versions/node/v8.16.0/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v8.16.0/bin/npm
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 4.2.1 - /usr/bin/gcc
    Git: 2.21.0 - /usr/local/bin/git
    Clang: 1100.0.33.8 - /usr/bin/clang
    Subversion: 1.10.4 - /usr/bin/svn
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
  IDEs:
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  Languages:
    Bash: 5.0.7 - /usr/local/bin/bash
    Python: 2.7.10 - /usr/bin/python
    Python3: 3.7.3 - /usr/local/bin/python3
    Ruby: 2.6.3 - /Users/andrew/.rvm/rubies/ruby-2.6.3/bin/ruby
```

**Comment by belemaire** [comment]
Hi @AndrewSouthpaw 
It seems like this is a problem with your env in some way. Wasn't able to repro locally using same version. Also this command is run to completion daily as part of automated system tests suite so would have caught a 'global' issue with this command.

Could you try re-running this command with the maximum log level enabled (trace), that might give use more details as to where the command is stalling.  One way to do that is just to that is to just run the command as follow : `ERN_LOG_LEVEL=trace ern create-miniapp fooMiniApp`.

**Comment by AndrewSouthpaw** [comment]
Thanks for the response! Here's [a gist](https://gist.github.com/AndrewSouthpaw/0570a332a16161b3abac4c6bda028dcb) of the output.

It looks like it's hanging on installation of CocoaPods. I'm wondering if that's hidden when I'm not running with `trace` on, and it's just waiting for a prompt that isn't shown to the user?

**Comment by friederbluemle** [comment]
Hi @AndrewSouthpaw - Can you try to install CocoaPods separately? On macOS: `brew install cocoapods`

**Comment by AndrewSouthpaw** [comment]
Yup that did the trick. Looks like there's a hidden dependency of this project. :-)

**Comment by AndrewSouthpaw** [comment]
Not sure how you'd like to handle that in your project... some options I'm seeing:

1. List as a dependency on the website and in docs (along with npm, etc.)
1. Throw an error if cocoapods is not installed and suggest a solution
1. Surface the prompt from the auto-installer and let it be run by the user

**Comment by friederbluemle** [comment]
Yes good point @AndrewSouthpaw - CocoaPods is a requirement of React Native since 0.60.x, and they already have it in their Getting Started guide: https://facebook.github.io/react-native/docs/getting-started
We should also mention this for Electrode Native. Thanks for your report and comments!

**Comment by belemaire** [comment]
Thanks much @AndrewSouthpaw for the feedback and suggestions 👍 
Unfortunately we didn't catch this one because we all have CocoaPods on our workstations and looks like our OSX CI env running the tests already comes with CocoaPods pre-installed :( 
Let's keep this issue open until properly addressed, I'll tackle it later on this week.

**Comment by AndrewSouthpaw** [comment]
Brilliant, thanks so much!
