### ISSUE TITLE
"ern cauldron" command fails: "Cannot read property 'devJsBundle' of undefined"

### ISSUE THREAD

**Issue by ryanliljestrom** [electrode-io/electrode-native#1468]
Currently, we have a crash when attempting to update a MiniApp in our cauldron after updating to electrode-native 0.38.13

We don't have any custom configurations. It looks like it's coming from https://github.com/electrode-io/electrode-native/blob/master/ern-orchestrator/src/container.ts#L117 . Other sections in the same code check if `containerGeneratorConfig` is defined before using, looks like it got missed here when `devJsBundle` support was added

<img width="833" alt="Screen Shot 2020-01-31 at 9 33 47 AM" src="https://user-images.githubusercontent.com/58603664/73553116-022e2c00-440f-11ea-9b85-483190c36bb7.png">

**Comment by belemaire** [comment]
Thanks @ryanliljestrom for reporting this one and doing some initial digging :+1:
You are totally right, this is the exact LOC that is causing the issue.
Will issue a PR to fix.
Meanwhile, as a workaround, while waiting for fix to be released, you could just update(or create if it doesn't exit) your cauldron `config/default.json` filewith an empty container generator config 
```
{
  [...other fields],
  "containerGenerator": {}
}
```

**Comment by belemaire** [comment]
@ryanliljestrom Just F.Y.I, fix was just released in [0.38.14](https://github.com/electrode-io/electrode-native/releases/tag/v0.38.14)
