### ISSUE TITLE
`ern regen-api` must clear the existing folders 

### ISSUE THREAD

**Issue by krunalsshah** [electrode-io/electrode-native#149]
`ern regen-api` must clear the existing folders except `schema.json` before re generating the api's.

**Comment by deepueg** [comment]
This was already done. There was an issue with IOS but that was fixed a while ago.

**Comment by belemaire** [comment]
@krunalsshah can you confirm and if that's the case please close this issue. thanks !

**Comment by krunalsshah** [comment]
@belemaire @deepueg 
Currently we delete the folders below.
```
shell.rm('-rf', path.join(outFolder, 'javascript'))
shell.rm('-rf', path.join(outFolder, 'swift'))
shell.rm('-rf', path.join(outFolder, 'android'))
shell.rm('-rf', path.join(outFolder, 'IOS'))
``` 

Which means that `package.json`, `yarn.lock` & `.flowconfig` are not deleted. For instance change to remove the `"prepublish": "ern regen-api -u same"`had to be made manually.
