### ISSUE TITLE
Test bridge with RN 0.49.0

### ISSUE THREAD

**Issue by belemaire** [electrode-io/electrode-native#150]
Ensure that bridge is compiling / tests are passing with `react-native@0.49.0` for both iOS and Android. 

Might need to regenerate bundle used in tests (or not if tests are passing fine with 0.48.0 bundle which might probably be the case).

- [x] iOS
- [x] Android

**Comment by clairewli** [comment]
Verified RN 49 works with iOS.

**Comment by belemaire** [comment]
Verified RN 49 works with Android. A code change is necessary for test to compile : https://github.com/electrode-io/react-native-electrode-bridge/pull/23

Once this PR is merged, I will check `Android` and close this issue

**Comment by belemaire** [comment]
#151 unlocked
