### ISSUE TITLE
Test iOS Container with RN 0.49.0

### ISSUE THREAD

**Issue by belemaire** [electrode-io/electrode-native#152]
Android has already been tested/updated properly.

**Comment by clairewli** [comment]
On it!

**Comment by belemaire** [comment]
@clairewli closing this one.
Forgot about it, but just updated getting started guide with MiniApps / platform bumped to `0.49.3`. Working fine on iOS, just had to create a new container injection configuration for React Native 0.49+ due to the introduction of the `fishook` library in RN 0.49.0 (container compilation was failing).https://github.com/electrode-io/electrode-native-manifest/pull/9
