### ISSUE TITLE
ern create-miniapp fails [Windows]

### ISSUE THREAD

**Issue by dig22** [electrode-io/electrode-native#1527]
`$ ern create-miniapp app`

`Error: spawn C:\Users\Zapcom_Intern\.ern\versions\0.39.0\node_modules\.bin\yarn ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)`

**Comment by IndianNative** [comment]
Facing same issue.
events.js:196
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Users\.ern\versions\0.40.0\node_modules\.bin\yarn ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:266:19)
    at onErrorNT (internal/child_process.js:468:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
    at onErrorNT (internal/child_process.js:468:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn C:\\Users\\.ern\\versions\\0.40.0\\node_modules\\.bin\\yarn',
  path: 'C:\\Users\\.ern\\versions\\0.40.0\\node_modules\\.bin\\yarn',
  spawnargs: [ 'info', 'test-miniapp', 'versions', '--json' ]
}

**Comment by IndianNative** [comment]
Anybody can help here? @friederbluemle @krunalsshah

**Comment by friederbluemle** [comment]
Hi @IndianNative and @dig22 - Would you be able to test using version `0.38.16` and let us know if you're still seeing the same issue?

```
ern platform use 0.38.16
```

Also, just checking: How did you install the Electrode Native CLI (e.g. using npm or Yarn)?

**Comment by IndianNative** [comment]
Hi @friederbluemle thanks for your response - Also I tried using version 0.38.16 but no luck. 

Also I installed it using npm.

**Comment by krunalsshah** [comment]
Thanks for writing back. I believe you are using Win OS.

Please confirm your node version. For curiosity sake please let us know the
yarn version.

Try running the command with ERN_LOG_LEVEL=trace & past the logs. thanks

**Comment by friederbluemle** [comment]
It appears to be an issue with spawn.. Can you also try to use bash for WSL?

**Comment by IndianNative** [comment]
Hi @krunalsshah .Yes I am using Win OS,. My current versions are
 electrode-native: 1.0.17
ern platform: 0.38.16
node version - 9.1.0
react-native-cli: 2.0.1

**Comment by IndianNative** [comment]
Hi @friederbluemle , tried git bash for the same but not solved.

![image](https://user-images.githubusercontent.com/50475442/77288128-27e3fd00-6cfd-11ea-8ef6-e34fd8f3f71b.png)

**Comment by friederbluemle** [comment]
Are you able to create a regular React Native app?

`npx react-native init test`

**Comment by IndianNative** [comment]
Ye I am able to create it successfully -
![image](https://user-images.githubusercontent.com/50475442/77409628-97321d80-6ddf-11ea-8502-9217bfb836ce.png)
![image](https://user-images.githubusercontent.com/50475442/77409664-a5803980-6ddf-11ea-8847-d7f2483d772d.png)

**Comment by IndianNative** [comment]
Hi @krunalsshah I tried using ERN_LOG_LEVEL=trace and found the logs -

events.js:288
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Users\\.ern\versions\0.38.16\node_modules\.bin\yarn ENOENT
[90m    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)[39m
[90m    at onErrorNT (internal/child_process.js:469:16)[39m
[90m    at processTicksAndRejections (internal/process/task_queues.js:84:21)[39m
Emitted 'error' event on ChildProcess instance at:
[90m    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)[39m
[90m    at onErrorNT (internal/child_process.js:469:16)[39m
[90m    at processTicksAndRejections (internal/process/task_queues.js:84:21)[39m {
  errno: [32m'ENOENT'[39m,
  code: [32m'ENOENT'[39m,
  syscall: [32m'spawn C:\\Users\\.ern\\versions\\0.38.16\\node_modules\\.bin\\yarn'[39m,
  path: [32m'C:\\Users\\.ern\\versions\\0.38.16\\node_modules\\.bin\\yarn'[39m,
  spawnargs: [ [32m'info'[39m, [32m'test-miniapp'[39m, [32m'versions'[39m, [32m'--json'[39m ]

**Comment by dig22** [comment]
> It appears to be an issue with spawn.. Can you also try to use bash for WSL?

@friederbluemle I tried using WSL (ubuntu 18.04) it works but gives another error mentioned below:
 
`Command yarn add react-native@0.60.6 --exact failed.`

(However unrelated to this issue i think)

This issue is only with respect to windows : cmd/powershell gets stuck on running the command and git-bash gives a spawn error.

electrode-native: v1.0.17
ern platform: v0.39.0
node version: v12.14.1

Thank you for assistance @IndianNative @friederbluemle @krunalsshah

**Comment by friederbluemle** [comment]
Thanks for reporting back @dig22 - Is there any additional output for the other error you're seeing?

**Comment by dig22** [comment]
@friederbluemle unfortunately no other log info apart from what @IndianNative found on git bash.

PowerShell gets stuck here : 

![ps1](https://user-images.githubusercontent.com/9392098/77612967-830d2e00-6f4f-11ea-9087-823784ecb858.PNG)

**Comment by friederbluemle** [comment]
@dig22 - Thanks for the screenshot. I have a Windows machine ready for testing and will check this either tomorrow or on the weekend (quite busy with work at the moment, so apologies for the delay).

**Comment by friederbluemle** [comment]
@dig22 @IndianNative - The issue is reproducible and we're looking into it. Will update you on the progress.

**Comment by friederbluemle** [comment]
@dig22 @IndianNative - Electrode Native version 0.40.2 was released just a couple of hours ago. It contains a fix related to running Yarn on Windows.

Can you please try again using the latest version:

```sh
ern platform use latest
```

Then, repeat the same command you used above.

```sh
ern create-miniapp app
```

**Comment by IndianNative** [comment]
Thanks @friederbluemle will check with latest version and update you soon. I was also occupied with other work so didn't get time to check this thread.

**Comment by friederbluemle** [comment]
Hi @IndianNative - Just checking real quick if you've had a chance to test it again with the latest version of ERN?
