### ISSUE TITLE
`ern run-ios` - packager fails if there is a space in the path

### ISSUE THREAD

**Issue by AndyIsaacson** [electrode-io/electrode-native#153]
I was running through the Quick Start, and had created the project in a directory called "Electrode Native" on my mac.  When I issued the `ern run-ios` command, the packager opened in a terminal window, but immediately failed saying the file wasn't found (unfortunately, I don't have the exact output anymore.)  When I renamed the directory to "ElectrodeNative", the packager started fine.

Something of an edge-case, for sure!

**Comment by deepueg** [comment]
@AndyIsaacson thanks for reporting this. We’ve been able to reproduce and identified the cause, working on a fix.

**Comment by belemaire** [comment]
Fix will be part of `Electrode Native v0.8.0` released next Monday (10/09)

**Comment by AndyIsaacson** [comment]
Nice!  Awesome turnaround :-)
