### ISSUE TITLE
ern run-android failing 

### ISSUE THREAD

**Issue by dig22** [electrode-io/electrode-native#1586]
Not sure why this is happening.

![err - Copy](https://user-images.githubusercontent.com/9392098/80562763-4fb63700-8a06-11ea-8ee8-44a9e88cb75d.GIF)

**Comment by friederbluemle** [comment]
Hi @dig22 - Can you add some environment info please?

```
node -v
yarn -v
```

**Comment by dig22** [comment]
node : v12.10.0
yarn : 1.22.0

**Comment by friederbluemle** [comment]
Thanks. Are you running in PowerShell? If you have WSL installed, could you check if that makes a difference?
Also: The project you are trying to build, is it hosted on GitHub? I also saw you have an active Cauldron. Can you share what it contains?

**Comment by dig22** [comment]
@friederbluemle the project/cauldron cannot be disclosed, however project is hosted on gitlab and i'm using a local cauldron

Yes, I'm using powershell,  I'll try using WSL soon

by the way is there a way is there a way to use ern link / ern start without the cauldron?

**Comment by dig22** [comment]
@friederbluemle It seems the runner looks for a package in Temp directory, could you explain me why it doing that so I can understand the situation better please.

**Comment by friederbluemle** [comment]
The temp directory is where ern generates the composites (containing the JavaScript that gets put into the container). Normally this process happens behind the scenes. I suspect some odd behavior related to the path name on Windows here. Will try to repro tomorrow.

**Comment by joshuafernandes1996** [comment]
![tempsnip](https://user-images.githubusercontent.com/36727430/81159443-97a90100-8fa6-11ea-939e-b560a517f86e.png)

If you notice it's trying to look for a folder called 'Watch' in Project Directory, but it seems like 
- the path is wrong 
- also, the path is concatenated without the '/'
- Why is it looking into the temp folder, while my Project dir is on Desktop

![tempsnip1](https://user-images.githubusercontent.com/36727430/81160180-63821000-8fa7-11ea-93c6-9f444e40eec3.PNG)

**Comment by friederbluemle** [comment]
Hi @joshuafernandes1996 - Thanks for the details. We are aware of the issue and a fix will be released soon!

**Comment by friederbluemle** [comment]
@dig22 - The issue described by @joshuafernandes1996 should be fixed by #1666. It will be available in the next release. Please check if this also helped with your problem and reopen if necessary. Thanks!
