### ISSUE TITLE
`ern run-ios` picks up older iOS version for simulator and breaks.

### ISSUE THREAD

**Issue by AndrewSouthpaw** [electrode-io/electrode-native#1588]
Repro:

1. Have an older (e.g. iOS 9) simulator installed, and run the simulator for an iPhone 6.
1. Have a more recent (e.g. iOS 12) simulator installed, and run the simulator for an iPhone 6.
1. Quit out of simulator. You should now have two simulators:

iOS 9

![Screen Shot 2020-04-29 at 1 34 07 PM](https://user-images.githubusercontent.com/5187404/80644232-2bfeeb00-8a1e-11ea-94ce-c10028fa1b20.jpg)

iOS 12

![Screen Shot 2020-04-29 at 1 34 11 PM](https://user-images.githubusercontent.com/5187404/80644248-30c39f00-8a1e-11ea-9ff5-12f19de0229d.jpg)

1. Run the following commands

```
$ ern create-miniapp WMCartMiniApp
$ cd WMCartMiniApp/
$ ern run-ios
 ___ _        _               _       _  _      _   _
| __| |___ __| |_ _ _ ___  __| |___  | \| |__ _| |_(_)_ _____
| _|| / -_) _|  _| '_/ _ \/ _` / -_) | .` / _` |  _| \ V / -_)
|___|_\___\__|\__|_| \___/\__,_\___| |_|\_\__,_|\__|_|\_/\___|
[v0.38.7] [Cauldron: -NONE-]

✔ Starting React Native Packager [http://192.168.1.72:8081] 0s
... snip ...
ℹ Killing all running Simulators
✔ Booting iOS Simulator 3s
✖ Building iOS Runner project 3s
✖ An error occurred: iOS Runner build failed [xcbuild exit code 70].
✖ To troubleshoot this build failure, we recommend building the Runner iOS project from Xcode.
✖ You can open the Runner project in Xcode manually or by running 'open ios/ErnRunner.xcodeproj'.
✖ Building the Runner from Xcode will provide more meaningful error reporting that can be of help
✖ to pinpoint the cause of the build failure.
```

It opens up simulator in iOS 9 for iPhone 6. By contrast, building through Xcode (11.3.1) works okay. It opens up the simulator in iOS 12 for iPhone 6.

If you repeat `ern run-ios` but choose a simulator where there's only recent iOS versions installed (> 12) then the problem goes away.

...

After some more digging, I'm realizing that the simulator chooser in `ern run-ios` is exhaustive, and if I match against the UID for the iOS 12 simulator then it works okay.

This was... rough to solve, and required some creativity. Perhaps the CLI could also print the iOS version, to make the choices more obvious?

**Comment by friederbluemle** [comment]
Thanks for the detailed report @AndrewSouthpaw :+1:

I assume you're talking about this interactive chooser here:

```
? Choose an iOS simulator (Use arrow keys)
❯ iPhone 8 (UDID 17043F85-C66D-405F-8D13-38460DEF27B6)
  iPhone 8 Plus (UDID 6B94537E-0E7C-4293-982F-BC12A7A3268D)
  iPhone 11 (UDID 28463F95-C420-429B-94D0-B25FD23049D1)
  iPhone 11 Pro (UDID F200BD5C-77CE-48D5-A2D0-FA952723A381)
  iPhone 11 Pro Max (UDID 8ED6419D-7069-46C9-9531-32BC60C0D107)
  iPhone SE (2nd generation) (UDID 535A2C2F-F20E-4069-A5B4-95A7567B0F1E)
  iPad Pro (9.7-inch) (UDID 716A758A-E400-4A92-8F8B-05D901964435)
(Move up and down to reveal more choices)
```

I tried to find the difference in the two screenshots you posted above, did you accidentally post the same one twice?

If I understand correctly, you want this list to also contain the iOS version, something like this?

```
? Choose an iOS simulator (Use arrow keys)
❯ iPhone 6 (iOS 9) (UDID 4212043B-A65D-4382-AC2A-BE9F5231E2DD)
  iPhone 6 (iOS 12) (UDID 8E9CF520-722C-40AF-AB43-97ED1DEF5998)
[...]
```
