### ISSUE TITLE
ern start after ern link fails 

### ISSUE THREAD

**Issue by dig22** [electrode-io/electrode-native#1604]
`An error occured: At least one MiniApp or JS API implementation is needed to generate a composite.`

**Comment by friederbluemle** [comment]
Can you provide some more details about your test setup please?

**Comment by dig22** [comment]
ern platform 0.40.5

steps to repro :
created and attached local cauldron 
added native app test:android:0.0.1
used `ern link` to link local miniapp for development 
used `ern start`

**Comment by dig22** [comment]
@friederbluemle I feel its not very clear that ern-start has to be used with `-m <mini-app-name>` after `ern link` for development environment

However this is working now with this flag, Thank you
