### ISSUE TITLE
Cannot find module 'boom'

### ISSUE THREAD

**Issue by kevinlho** [electrode-io/electrode-native#171]
ive tried to follow the quick start tutorial in the following link
'http://www.electrode.io/site/docs/getting_started.html'

# when i run '_ern create-miniapp MovieListMiniApp_':
$ ern create-miniapp MovieListMiniApp
module.js:471
    throw err;
    ^

Error: Cannot find module 'boom'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/kevin/.ern/versions/0.7.0/node_modules/ern-cauldron-api/dist/util.js:24:13)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)

# same with 'ern':
$ ern
module.js:471
    throw err;
    ^

Error: Cannot find module 'boom'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/kevin/.ern/versions/0.7.0/node_modules/ern-cauldron-api/dist/util.js:24:13)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

# installation progress
$ sudo npm install -g electrode-native && ern
/usr/bin/ern -> /usr/lib/node_modules/electrode-native/bin/ern.js
/usr/lib
└─┬ electrode-native@1.0.9 
  ├─┬ chalk@1.1.3 
  │ ├── ansi-styles@2.2.1 
  │ ├── escape-string-regexp@1.0.5 
  │ ├─┬ has-ansi@2.0.0 
  │ │ └── ansi-regex@2.1.1 
  │ ├── strip-ansi@3.0.1 
  │ └── supports-color@2.0.0 
  ├─┬ ora@1.3.0 
  │ ├─┬ cli-cursor@2.1.0 
  │ │ └─┬ restore-cursor@2.0.0 
  │ │   ├─┬ onetime@2.0.1 
  │ │   │ └── mimic-fn@1.1.0 
  │ │   └── signal-exit@3.0.2 
  │ ├── cli-spinners@1.1.0 
  │ └── log-symbols@1.0.2 
  └─┬ update-notifier@1.0.3 
    ├─┬ boxen@0.6.0 
    │ ├── ansi-align@1.1.0 
    │ ├── camelcase@2.1.1 
    │ ├── cli-boxes@1.0.0 
    │ ├── filled-array@1.1.0 
    │ ├── object-assign@4.1.1 
    │ ├─┬ repeating@2.0.1 
    │ │ └─┬ is-finite@1.0.2 
    │ │   └── number-is-nan@1.0.1 
    │ ├─┬ string-width@1.0.2 
    │ │ ├── code-point-at@1.1.0 
    │ │ └── is-fullwidth-code-point@1.0.0 
    │ └── widest-line@1.0.0 
    ├─┬ configstore@2.1.0 
    │ ├─┬ dot-prop@3.0.0 
    │ │ └── is-obj@1.0.1 
    │ ├── graceful-fs@4.1.11 
    │ ├─┬ mkdirp@0.5.1 
    │ │ └── minimist@0.0.8 
    │ ├── os-tmpdir@1.0.2 
    │ ├── osenv@0.1.4 
    │ ├── uuid@2.0.3 
    │ └─┬ write-file-atomic@1.3.4 
    │   ├── imurmurhash@0.1.4 
    │   └── slide@1.1.6 
    ├── is-npm@1.0.0 
    ├─┬ latest-version@2.0.0 
    │ └─┬ package-json@2.4.0 
    │   ├─┬ got@5.7.1 
    │   │ ├─┬ create-error-class@3.0.2 
    │   │ │ └── capture-stack-trace@1.0.0 
    │   │ ├── duplexer2@0.1.4 
    │   │ ├── is-redirect@1.0.0 
    │   │ ├── is-retry-allowed@1.1.0 
    │   │ ├── is-stream@1.1.0 
    │   │ ├── lowercase-keys@1.0.0 
    │   │ ├── node-status-codes@1.0.0 
    │   │ ├─┬ parse-json@2.2.0 
    │   │ │ └─┬ error-ex@1.3.1 
    │   │ │   └── is-arrayish@0.2.1 
    │   │ ├─┬ pinkie-promise@2.0.1 
    │   │ │ └── pinkie@2.0.4 
    │   │ ├── read-all-stream@3.1.0 
    │   │ ├─┬ readable-stream@2.3.3 
    │   │ │ ├── core-util-is@1.0.2 
    │   │ │ ├── inherits@2.0.3 
    │   │ │ ├── isarray@1.0.0 
    │   │ │ ├── process-nextick-args@1.0.7 
    │   │ │ ├── string_decoder@1.0.3 
    │   │ │ └── util-deprecate@1.0.2 
    │   │ ├── timed-out@3.1.3 
    │   │ ├── unzip-response@1.0.2 
    │   │ └─┬ url-parse-lax@1.0.0 
    │   │   └── prepend-http@1.0.4 
    │   ├─┬ registry-auth-token@3.3.1 
    │   │ ├─┬ rc@1.2.1 
    │   │ │ ├── deep-extend@0.4.2 
    │   │ │ ├── ini@1.3.4 
    │   │ │ ├── minimist@1.2.0 
    │   │ │ └── strip-json-comments@2.0.1 
    │   │ └── safe-buffer@5.1.1 
    │   └── registry-url@3.1.0 
    ├── lazy-req@1.1.0 
    ├─┬ semver-diff@2.1.0 
    │ └── semver@5.4.1 
    └─┬ xdg-basedir@2.0.0 
      └── os-homedir@1.0.2 

✔ Hurray ! Electrode Native v0.7.0 was successfully installed.

# node and npm version
$ node -v
v6.11.4
$ npm -v
3.10.10

**Comment by belemaire** [comment]
@kevinlho : thanks a lot for reporting this issue.
Fixed it in https://github.com/electrode-io/electrode-native/pull/172
Will be shipped in `v0.8.0` of electrode native that we plan on releasing tomorrow. good timing. 
sorry for the inconvenience.
