### ISSUE TITLE
Android container creation and SYSTEM_ALERT_WINDOW permission

### ISSUE THREAD

**Issue by Fabiolino88** [electrode-io/electrode-native#1711]
Hi guys, 

I'm writing today to ask a question about the SYSTEM_ALERT_WINDOW.
At the moment we are generating the container using:
`ern create-container --descriptor <product>:android:<version> --platform android`

and then we deploy the container using maven.

Once we add the maven package to our project the merged manifest has the SYSTEM_ALERT_WINDOW permission in it. As a consequence when we try to submit our app, google play is flagging a warning for the newly added permission.

Questions:
for what is electrod container using the SYSTEM_ALERT_WINDOW permission?
is it something used only for debug purposes ? if yes, why is it appearing in the release container manifest ?

Please let me know if you need more details.
Thanks in advance :)

**Comment by friederbluemle** [comment]
Hi @Fabiolino88 - Yes, that is correct, `SYSTEM_ALERT_WINDOW` should _not_ be part of the release container.

We already made some changes to the container hull that [removed](https://github.com/electrode-io/electrode-native/pull/1629/files#diff-ff688836c6965c962fecd267cef7ce2cL4) the permission (merged in #1629), available in ERN 0.42.0 or later.
Which version of ERN are you using?

**Comment by Fabiolino88** [comment]
Hi @friederbluemle, 
thanks for your reply.

Ok, we are currently using ERN 0.41.6. We'll try to upgrade and regenerate the container for the next release.
For now we just added the following line in our manifest:
`<uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW" tools:node="remove"/>`

Thanks
