### ISSUE TITLE
Cannot "ern link" with a cauldron: "Unable to resolve module 'undefined' from 'index.ios.js'"

### ISSUE THREAD

**Issue by ryanliljestrom** [electrode-io/electrode-native#1713]
We are running into an issue on `0.43.0` where we can no longer run `ern link` with a remote ~composite~ cauldron. Our previous version (where it was working fine) was `0.40.5`.

After we launch the packager and build the app, we get the error mentioned in the description:

`Unable to resolve module 'undefined' from 'index.ios.js'`

If I look at the composite generated in the temporary directory, there is an `import 'undefined'` where I would expect `import '@scoped/my-miniapp'`. It does look like the `@scoped/my-miniapp` is properly copied into `node_modules`

**Comment by belemaire** [comment]
Once again, thanks for the clear details 👍 
This greatly helped to reproduce the issue. Working a fix.
