### ISSUE TITLE
Not picking the manifest repo I listed in the config of cauldron.json

### ISSUE THREAD

**Issue by cjoshi85** [electrode-io/electrode-native#1756]
I added manifest.json url with partial as true. But when I add any dependency ,it is just looking at the electrode-native-manifest.git and not on my custom repo.
I followed the steps provided in the documentation, but still no luck. Can anyone help to resolve this

**Comment by LcTwisk** [comment]
Seems to be working for me on the latest version. Would you mind sharing how you've added the manifest override? I might be able to help.

**Comment by cjoshi85** [comment]
Thanks for the quick reply. I have added below in my cauldron.json file.

**Comment by LcTwisk** [comment]
I see we don't have our config added to the `cauldron.json` itself. Instead, I've got a folder named `config` with a file called `default.json` inside it. This file should contain this in your case:
```json
{
  "manifest": {
    "override": {
      "url": "git@github.com:medtrail/medtrail-electrode-native-manifest.git",
      "type": "partial"
    }
  }
}
```

So I've got the following files in the cauldron repo:
`cauldron.json`
`config/default.json`

Let me know if it works!

**Comment by cjoshi85** [comment]
Thank you @LcTwisk , it seems to pick from my repo now. But I am getting below error while fetching the package. Can you please help here? is it because my repo is private?

```[ Syncing git@github.com:medtrail/medtrail-electrode-native-manifest.git Manifest (Failed) ]
✖ An error occurred: fatal: couldn't find remote ref master
Error: fatal: couldn't find remote ref master

**Comment by LcTwisk** [comment]
Might be a stupid question but did you push a master branch to your manifest repo?

**Comment by cjoshi85** [comment]
Ohh no. Actually git switched to main from master as default now, so it didn't pick it. Anyway I have created master branch now and it seems to be working now. Again thanks a lot for quick help!

**Comment by friederbluemle** [comment]
> Actually git switched to main from master as default now

Minor correction: _Git**Hub**_ switched to `main`. Git uses [`master` as the default](https://github.com/git/git/blob/30b29f044a2b30f0667eb21559959e03eb1bd04f/refs.c#L591). If you want to avoid confusion and decrease entropy, you can simply update the newly added configuration option on GitHub to match Git's default `master` here: https://github.com/settings/repositories

Issue seems to be resolved. Thanks @LcTwisk for helping out!

**Comment by zeallat** [comment]
Our documentation might be out of date
https://github.com/electrode-io/electrode-native/blob/master/docs/platform-parts/manifest/override.md
