### ISSUE TITLE
Cannot create plugin for modules written in Kotlin

### ISSUE THREAD

**Issue by ryanliljestrom** [electrode-io/electrode-native#1757]
Whenever I attempt to create a plugin for a third-party package that contains Kotlin (e.g., https://github.com/stashenergy/react-native-msal) it always fails in https://github.com/electrode-io/electrode-native/blob/3bc17330d3d0d9ad94dde523baf096cada954a1c/ern-core/src/AndroidPluginConfigGenerator.ts#L154 . 

Looks like it needs some tweaks to look for `*Package.kt` files as well, plus some additional parsing of the Kotlin files as well.

**Comment by friederbluemle** [comment]
Hi @ryanliljestrom - Thanks for opening this issue!
At this point there is no support for Kotlin in React Native **native modules** used with Electrode Native. 

More details about the current and potential future support for Kotlin in React Native/Electrode Native:

> Electrode Native is a platform that builds on top of React Native. React Native itself currently does not have any Kotlin dependencies or code (neither in the core native modules, nor in the default template used to create a new RN app). While it is possible to use Kotlin in an _application_ project (one that uses React Native, as well as Electrode Native), the situation for _native modules_ is slightly different. This is mainly due to the unconventional way in which React Native libraries (specifically, the Android native modules) are distributed and consumed by application projects. Instead of the "regular" way of distributing precompiled (binary) artifacts for native code, RN dependencies with their native modules are distributed as zip files and extracted into node_modules. They are then taken in source form from there and compiled on the fly - Because all these dependencies are standalone projects, not directly aware of each other, the probability for conflicts increases with every additional dependency.
Electrode Native has to support hundreds of possible plugins/React Native dependencies, and ideally any arbitrary combination of them. To minimize the risk of conflicts, we require it to be as closely aligned with core React Native as possible. That said, we continue to monitor the situation, and should there be a major change in core React Native, you can expect a similar update for Electrode Native soon thereafter.

**Comment by friederbluemle** [comment]
@ryanliljestrom - I've opened a PR in [`react-native-msal`](https://github.com/stashenergy/react-native-msal) converting the native module code to plain Java and **removing** the dependency on `kotlin-stdlib`. If everything goes well it should get merged this weekend. Once a new release is out, the dependency should be ready to use with a plugin config.

https://github.com/stashenergy/react-native-msal/pull/61

**Comment by ryanliljestrom** [comment]
Wow, that’s fantastic! I appreciate the PR and am glad that the [react-native-msal](https://github.com/stashenergy/react-native-msal) devs are so responsive. Hypothetically if they weren’t, could the `applyPatch` plugin configuration be used to do the same thing without a PR?

**Comment by friederbluemle** [comment]
> Hypothetically if they weren’t, could the `applyPatch` plugin configuration be used to do the same thing without a PR?

That's a very interesting idea. I haven't given that potential path much thought, but good to keep in mind. :+1:

**Comment by josmithua** [comment]
Just released v3.0.4 of react-native-msal without kotlin. Hopefully that solves your problem for now Ryan. Let me know if there's anything more we can do to help.

**Comment by friederbluemle** [comment]
Awesome, thank you so much @josmithua 💯 👍

**Comment by friederbluemle** [comment]
Primary platform support was added in #1807, and #1824 will add additional support to the plugin config generator.
