### ISSUE TITLE
xcrun error: "instruments", not a developer tool or in PATH

### ISSUE THREAD

**Issue by ozcanzaferayan** [electrode-io/electrode-native#1832]
When I run 'ern run-ios',  this throws an error:
✖ An error occurred: Command failed: xcrun instruments -s
✖ xcrun: error: Failed to locate 'instruments'.
✖ xcrun: error: unable to find utility "instruments", not a developer tool or in PATH

I think its related with Xcode Versions. How can I fix it?

**Comment by friederbluemle** [comment]
Hi @ozcanzaferayan - Thank you for your report. We are aware of the issue, currently `run-ios` is not compatible with Xcode 13. We have a fix in progress, a new version of ern should be ready soon. I'll keep you posted here.

**Comment by ozcanzaferayan** [comment]
Thanks, this is exactly what I was looking for.
