### ISSUE TITLE
Container generator stuck with Node.js 17+

### ISSUE THREAD

**Issue by friederbluemle** [electrode-io/electrode-native#1837]
Still needs to be investigated more, but it appears in some cases, container generation (e.g. `ern create-container`, or running a miniapp) with Node.js 17 simply stops, with no more console output, waiting forever.

It happens at the end of the `Injecting JavaScript engine` step, right _before_ the line starting with `cp` below:

```
popd
~/.ern/containergen/out/android /path/to/test-miniapp
cp -Rf /private/var/folders/xb/4lt2zppd3cnc6qhcc09wxb8r0000gn/T/tmp-92135-YPGFhV9Qp5gE/jni ~/.ern/containergen/out/android/lib/src/main/jniLibs
[ Injecting JavaScript engine [JavaScriptCore] (Completed in 0s)]
```

**Comment by friederbluemle** [comment]
This also affects commands that depend on container generation (e.g. `ern run-android`).

**Comment by bdsines** [comment]
@friederbluemle - I am facing the same issue. Are there any resolution/workarounds for this issue?
<img width="904" alt="image" src="https://user-images.githubusercontent.com/26282753/186208416-218ed26b-35d4-44f7-85d5-5af482100624.png">

**Comment by bdsines** [comment]
any help on this? I tried by changing the node version to 16 on my macbook M1 but still have the same issue

**Comment by quanghoang0101** [comment]
Same problem! Any helps?

**Comment by quanghoang0101** [comment]
I have detected the issue. The problem with compressed-zib lib. OnExtract is not called so it waits forever.

**Comment by friederbluemle** [comment]
Great thank you very much for the investigation @quanghoang0101 - A third party dependency has also been my suspicion as the culprit of this error.

I've replaced compress-zip with adm-zip in #1878
