### ISSUE TITLE
An error occurred: At least one MiniApp or JS API implementation is needed to generate a composite

### ISSUE THREAD

**Issue by crazySadSoul** [electrode-io/electrode-native#1865]
I want to create a container:

First i init a miniapp with Electrode-native Cli.
then i run command with "ern run-android" cli was successful.
      1. i create a Github Repository for Cauldron;
      2.  ern cauldron add nativeapp testelectrodenative-miniapp:android:0.0.1;
      3.  ern create-container, i got two errors: 
           1. "An error occurred: At least one MiniApp or JS API implementation is needed to generate a composite";
           2. "runCauldronCompositeGen failed: Error: At least one MiniApp or JS API implementation is n
eeded to generate a composite";
      4. At least , i run "ern start" and "ern create-composite", i got the error "An error occurred: At least one MiniApp or JS API implementation is needed to generate a composite";
      
Can you guys tell me the step for the create container!
Please help!!!!!!!!!!

**Comment by crazySadSoul** [comment]
@belemaire 
When i run "ern create-composite", i got this error: 
"An error occurred: At least one MiniApp or JS API implementation is needed to generate a composite"

**Comment by crazySadSoul** [comment]
i want to build a aar module

**Comment by leekuo** [comment]
Hi @crazySadSoul try this command to create a container:
`ern create-container --miniapps /absolute/path/to/miniapp_directory --platform ios|android`
for composites you may want to try this one:
`ern create-composite -m /absolute/path/to/miniapp1_directory /absolute/path/to/miniapp2_directory`

Let me know if that helps or not.

**Comment by crazySadSoul** [comment]
<img width="566" alt="image" src="https://user-images.githubusercontent.com/26052793/197439424-19a509cb-b290-42e7-8072-f0d6eec5bdae.png">
@leekuo Hi, i run "ern create-container --miniapps /absolute/path/to/miniapp_directory --platform ios|android" this command, i got this error

**Comment by crazySadSoul** [comment]
> Hi @crazySadSoul try this command to create a container: `ern create-container --miniapps /absolute/path/to/miniapp_directory --platform ios|android` for composites you may want to try this one: `ern create-composite -m /absolute/path/to/miniapp1_directory /absolute/path/to/miniapp2_directory`
> 
> Let me know if that helps or not.

It work for me! Thank you!
But  i cant find aar module in the generated  directory.

<img width="797" alt="image" src="https://user-images.githubusercontent.com/26052793/197456661-4e32ea6d-9e98-4dac-9a6d-8063a3df2729.png">

**Comment by leekuo** [comment]
> It work for me! Thank you! But i cant find aar module in the generated directory.
> 
> <img alt="image" width="797" src="https://user-images.githubusercontent.com/26052793/197456661-4e32ea6d-9e98-4dac-9a6d-8063a3df2729.png">

@crazySadSoul Try running the publish container to your local Maven repository, for example:
`ern publish-container -p maven --platform android -e '{"groupId":"com.walmart.ern","artifactId":"quickstart"}'`

Then look inside your $HOME/.m2 folder and locate the generated AAR artifact there.

**Comment by crazySadSoul** [comment]
@leekuo its successful to generated aar module.  👍

**Comment by leekuo** [comment]
That is awesome, great to hear!
