### ISSUE TITLE
Error: Command failed: ./gradlew lib:uploadArchives

### ISSUE THREAD

**Issue by kevinlho** [electrode-io/electrode-native#190]
executing `ern run-android` on Linux Mint 18.2 Cinnamon x64
error message:

```
$ ern run-android

| __| |___ __| |_ _ _ ___  __| |___  | \| |__ _| |_(_)_ _____ 
| _|| / -_) _|  _| '_/ _ \/ _` / -_) | .` / _` |  _| \ V / -_)
|___|_\___\__|\__|_| \___/\__,_\___| |_|\_\__,_|\__|_|\_/\___|
[v0.8.0] [Cauldron: -NONE-]
✔ Starting React Native packager
✔ Preparing MiniApp(s) and running compatibility checks
⠙ Creating local Container and publishing AAR to maven localError: Command failed: ./gradlew lib:uploadArchives 

[buildAndPublishAndroidLib] Something went wrong: Error: Command failed: ./gradlew lib:uploadArchives 

[generateContainer] Something went wrong. Aborting Container Generation
✖ Error: Command failed: ./gradlew lib:uploadArchives 

runLocalContainerGen failed: Error: Command failed: ./gradlew lib:uploadArchives 

Error: Command failed: ./gradlew lib:uploadArchives 

```

**Comment by kevinlho** [comment]
running emulator before executing `ern run-android` solved this problem.

**Comment by krunalsshah** [comment]
@kevinlho You shouldn't require to have the emulator running prior to execute `ern run-android` , if there is no emulator running it will prompt you to pick one from the `avd` list.
Happy to chat more, Can you please provide your execution environment?

**Comment by belemaire** [comment]
@kevinlho We don't officially support Linux -yet-. Only OSX is officially supported.
That being said, we are currently in an effort of refactoring Electrode Native codebase to make it truly cross-platform, with Windows support in mind first. Linux should not be too hard to tackle as it is way closer to OSX than Windows is ;)
More news to come regarding this cross-platform support very soon, but as of now any issue on Linux or Windows won't be investigated further as support is not really there.
