### ISSUE TITLE
When building iOS host app, header files cannot be located

### ISSUE THREAD

**Issue by anthonywebb** [electrode-io/electrode-native#195]
I'm not sure if this is an issue with the container, or with xcode itself.  But after walking through the guide for importing my container into a fresh iOS project.  When I try to build I am seeing several missing headers like the one in this screenshot.  Is there some additional configuration of the iOS project required beyond what is in the docs? Thanks!

<img width="847" alt="screen shot 2017-10-13 at 10 30 30 am" src="https://user-images.githubusercontent.com/4397/31556371-fb2fe78e-b001-11e7-9864-42999236be41.png">

A top level view of some others that are missing too:
<img width="1143" alt="screen shot 2017-10-13 at 10 35 59 am" src="https://user-images.githubusercontent.com/4397/31556463-689b0f42-b002-11e7-8be9-ee445048c061.png">

**Comment by deepueg** [comment]
@anthonywebb Thanks for reporting the issue.

Are you performing a manual installation of the container in your project?
Please confirm if you are following the steps detailed [here](https://electrode.gitbooks.io/electrode-native/content/platform-parts/container.html#adding-a-container-to-your-mobile-application). ?

**Comment by anthonywebb** [comment]
@deepueg yes we are using the manual installation instructions found on that page.  Pretty straight forward so I am not sure what we are missing.  Can you tell me.  Once I clone the container to your machine, should I be able to open the XCodeProj of that container and build it without errors?  I would assume so, but I am currently unable to build it so the issues may be related?

**Comment by deepueg** [comment]
Yes, you should be able to build the container project.! But from the screenshot above it looks like you are building native project after adding the container to it, pls confirm?

Also, Can you try to do the following steps?

1. Build the container project separately and see if it builds without errors?
2. if 1 succeeds, manually add this to your native project and try to build it?

**Comment by anthonywebb** [comment]
@deepueg You are correct, this issue was when trying to run the container in a host app. I have another issue open that is discussing the inability to build the container.  I am trying to build a new container from scratch to see if I can repro the problem https://github.com/electrode-io/electrode-native/issues/193

**Comment by amloelxer** [comment]
@anthonywebb @deepueg I have the same problem. I'm trying to add a container to my existing native application, but keep getting errors. When trying to build the container separately, I get this error, among others having to do with React/RCTBridge
 ```
/out/ios/ElectrodeContainer/Libraries/ReactNative/ActionSheetIOS/RCTActionSheetManager.m:10:
/Users/alex/Desktop/container/out/ios/ElectrodeContainer/Libraries/ReactNative/ActionSheetIOS/RCTActionSheetManager.h:12:9: fatal error: 'React/RCTBridge.h' file not found
#import <React/RCTBridge.h>
        ^~~~~~~~~~~~~~~~~~~
1 error generated.
```
I'm on Xcode version 9.0 and Mac OS 10.12.6. Any other info I can provide you guys to help remedy this problem? Thanks!

**Comment by anthonywebb** [comment]
@amloelxer thank you for confirming! @deepueg I am happy to report that after publishing a fresh container and cloning that, I am able to build that without any issues at all!  Sadly, it did not seem to fix the missing header issue in my host app.

One note, in the manual import instructions for iOS, step 2, you mention "Open your project in Xcode and right click on Libraries." however, in a fresh xcode app that is created (single page template) I can not find "libraries" anywhere in the UI.  So I have just been right clicking on the project and choosing 'Add files to "myproject"' and from there selecting the xcodeproj file.  The rest of the steps make perfect sense and I am following them correctly.

**Comment by anthonywebb** [comment]
@amloelxer @deepueg we've got the host app to finally work.  The trick for us was to after adding the container to your host project, to go in an kick off a build of that container from within the host project.  This can be done by clicking on pencil icons up near the run/top buttons in the upper left of the UI, choosing electrode container, then choose something like iphone8, and hit the run button.  Once your project has been built, switch back to your host project and it will run like a champ.

<img width="796" alt="screen shot 2017-10-13 at 1 25 21 pm" src="https://user-images.githubusercontent.com/4397/31562935-7d759a96-b01a-11e7-8c89-628d2b7472e9.png">

**Comment by clairewli** [comment]
@anthonywebb based on the solution you provided above, it sounds like your project has `parallel build` enabled. If you disable that, it should build `ElectrodeContainer` first and then build your host app. In that case, you won't have to manually build `ElectrodeContainer` first.

**Comment by anthonywebb** [comment]
@clairewli Cool, where is this "parallel build" flag located?  Would you like me to make a note in the getting started docs or will someone one your team be on that?

**Comment by clairewli** [comment]
@anthonywebb  in the getting started docs, we have control over the `ErnRunner.xcodeproj` project settings, so I made sure that the flag is unchecked. But yeah, thanks for bringing up. I should include that in the `import container to your own project` docs. To uncheck `parallel build`, do the following: (choose your host app target) Product -> Scheme. In the pop-up window, left panel find `Build` and then you should see `Build Options` just uncheck `Parallelize Build`

**Comment by anthonywebb** [comment]
Thanks for the help everyone!  Found it. Product -> Scheme (make sure the checkmark is next to your host app), then select "edit scheme". In the pop up window select "Build" and uncheck the "Parallelize Build" option. 

<img width="988" alt="screen shot 2017-10-13 at 1 53 18 pm" src="https://user-images.githubusercontent.com/4397/31563886-2a5a9952-b01e-11e7-99c5-8f2739a1ea76.png">

**Comment by deepueg** [comment]
@anthonywebb Thank you. We will add some notes regarding this in out docs.!
