### ISSUE TITLE
Host app in debug mode, nothing running on 8081

### ISSUE THREAD

**Issue by anthonywebb** [electrode-io/electrode-native#196]
We have our host app running.  When we initialize the project we set debugEnabled = YES like so:
```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {

    ElectrodeContainerConfig *containerConfig = [[ElectrodeContainerConfig alloc] init];
    containerConfig.debugEnabled = YES;
    [ElectrodeReactNative startWithConfigurations:containerConfig];
    
    return YES;
}
```

When running in debug mode, the app is hunting for the dev server on 8081 but cant find it.  Is there a step in the process we are missing in order to run with debugEnabled?  It is asking that we run npm start to enable that, but from where should we run that command?

<img width="407" alt="screen shot 2017-10-13 at 1 22 10 pm" src="https://user-images.githubusercontent.com/4397/31563209-5a9f2fcc-b01b-11e7-9501-6bc8edae1c39.png">

It is worth noting that if containerConfig.debugEnabled = NO; then our code seems to run fine (which is awesome!)

**Comment by clairewli** [comment]
from the root of your miniapp directory. can you try run `npm start`

**Comment by anthonywebb** [comment]
Hmm, ok yea the packager is running, and I even pulled the URL from the xcode console and hit it in my browser to verify that it was serving stuff.  Really strange.

<img width="1090" alt="screen shot 2017-10-13 at 2 02 24 pm" src="https://user-images.githubusercontent.com/4397/31564259-674f9b54-b01f-11e7-92ed-7a410c748755.png">

**Comment by anthonywebb** [comment]
Found the issue! By default http traffic is blocked in your host application.  This means that it will not be able to reach the packager (which is hosted http). Once you allow http requests everything will work: https://stackoverflow.com/questions/31254725/transport-security-has-blocked-a-cleartext-http

@clairewli should probably make a note of this in the manual install docs as well.

**Comment by clairewli** [comment]
hey @anthonywebb thanks for the note!

**Comment by belemaire** [comment]
@anthonywebb @clairewli 
Thanks, that's indeed something missing in our documentation.
The problem is not happening with the Runner though, as we have added the necessary permissions in it https://github.com/electrode-io/electrode-native/blob/master/ern-runner-gen/runner-hull/ios/ErnRunner/Info.plist#L44...L48
