### ISSUE TITLE
Cauldron transactions should create a single git commit

### ISSUE THREAD

**Issue by belemaire** [electrode-io/electrode-native#227]
Cauldron client is creating commits for each atomic operations, resulting in a lot of verbosity when running Cauldron transactions. 

For example, updating a MiniApp version results in 5 commits. Creating a new native application version in the Cauldron ends up in a huge number of commits as well.

High level transactions (adding/removing/updating MiniApp(s) and/or Dependency(ies)) should end up in a single transactional commit instead, to make it easier to see the changes and reduce commit history verbosity.

**Comment by krunalsshah** [comment]
👍 pls let me know if you'd want to offload work :)
