### ISSUE TITLE
create-api-impl should allow arbitrary implementation naming

### ISSUE THREAD

**Issue by belemaire** [electrode-io/electrode-native#254]
- [x] Add new option to `create-api-impl` command to pass name of api implementation (completely replacing the convention). If user provide `test-api-implementation`, it will use this name as such.
- [x]  support scope
- [x] Update logic in `ern-api-impl-gen` accordingly
- [x] Update platform logic where needed to not rely on naming to detect API implementation module, but on the data we store in `ern` object in package.json of the module (indicating the type of `ern` module)
- [x] Update `create-api-impl` command documentation

**Comment by krunalsshah** [comment]
@belemaire did you mean keeping the command `ern create-api-impl <api>` as is & introduce option such as `--apiImplName/n` to pass the impl name ? meaning the command will look like `ern create-api-impl react-native-movie-api -n reactive-native-my-movie-impl`

**Comment by belemaire** [comment]
Yes let's do it this way for now. 

We might (or might not) later on (should not be part of this PR) also prompt the user for a name (and use the default generated one as the default one if user press enter). But for this PR what you suggest is exactly what is needed.
