### ISSUE TITLE
Introduce bundle command

### ISSUE THREAD

**Issue by belemaire** [electrode-io/electrode-native#261]
To create a composite MiniApp / bundle we use the `create-container --js` command.
It is not very intuitive and complexify logic (and options) for this command.

We should introduce a new command `bundle` that does this job instead. `bundle` command might accept some of the same options as `react-native bundle`.

**Comment by jomnius** [comment]
Just checking, if anything is happening with this issue. So, any plans?

**Comment by belemaire** [comment]
This issue has not been prioritized yet. 

That being said, if your goal is to just generate the JS bundle which contain all MiniApp(s) (what this command would achieve), you can do it in the following way :

- Use `create-container` command with the `--js` flag, in addition to the other regular command options you would use.This will generate the composite MiniApp JS project. You should also use the `--outDir` option to specify the directory where the resulting project will be stored.
- Go to the  directory where the composite was generated (`outDir`) and then you can use `react-native bundle` directly from within this folder, to create the JS bundle.

The `ern bundle` mentioned in this issue would actually proceed in a similar manner, it would just combine these 2 steps in a single command.

**Comment by jomnius** [comment]
Thanx for reply, appreciated! My goal is CI/CD for electrode native project and I've gotten as far as trying to "build" the project using "ern run-android" command (and failing as expected).

Thanx to your tip I now realise that I can actually use react native commands as backup :) Will dig out my previous experiment with Fastlane for RN project and try to use that with current ERN project.

**Comment by belemaire** [comment]
Moving this one to our backlog
