### ISSUE TITLE
Store more CodePush related information in Cauldron

### ISSUE THREAD

**Issue by belemaire** [electrode-io/electrode-native#302]
We currently store a minimal amount of information pertaining to CodePush updates in the Cauldron (just the list of MiniApps that were CodePushed). 

We need to keep more information in addition to the MiniApps names/versions :

- The flags / options that were used to push the update
- The deployment key that was used (one of the parameters to CodePush command). ex: Production, QA, Staging ...

For the CodePush execution logic we also need to distinguish between the different deployment keys and use the proper yarn.lock from the Cauldron (right now we have a single yarn.lock which is not right when different envs are used).

Should figure out the proper object schema and conduct the implementation.

**Comment by krunalsshah** [comment]
This is a very nice extension to the code push command support
