### ISSUE TITLE
CLI flags mutate configuration file

### ISSUE THREAD

**Issue by swashcap** [electrode-io/electrode-native#329]
I noticed this strange `pwd` output:

![pwd-pwd](https://user-images.githubusercontent.com/1858316/32637129-ec9f3dac-c56c-11e7-91b4-a28e5ad1baf2.jpg)

That’s likely from shelljs because it's [set to verbose](https://github.com/electrode-io/electrode-native/blob/533a9c772e8251dd1726ab5f4e72fdac02cfb18c/ern-local-cli/src/index.js#L53). How did my `logLevel` get set to `trace`?!

It turns out that electrode-native [mutates configuration based on flags](https://github.com/electrode-io/electrode-native/blob/533a9c772e8251dd1726ab5f4e72fdac02cfb18c/ern-local-cli/src/index.js#L59-L70). I’d say this is totally unexpected behavior: flags typically configure output for the command being run, and usually don't modify a user's settings. Can we remove this functionality? Could we expose it via a `ern config set <option> <value>` API instead?

**Comment by krunalsshah** [comment]
http://www.electrode.io/site/docs/getting_started.html

**Comment by krunalsshah** [comment]
ern platform config <key> [value] command?

**Comment by belemaire** [comment]
Agreed.
We already have a way to persist/retrieve local configuration key/value pairs through [ern platform config](https://electrode.gitbooks.io/electrode-native/cli/platform/config.html) command.
These flags are already relying on this configuration store ...

Let's remove these flags and rename the stored keys appropriately.

Would then update their value through :

```console
$ ern platform config show-banner [true|false]
$ ern platform config log-level [trace|debug|warn|info|fatal]
```

Does the naming of the config keys makes sense (`show-banner` and `log-level`) makes sense or any other better naming idea for these ones ?

Setting up milestone to `v0.11.0` for this one.
