### ISSUE TITLE
MiniApp hosted in an Android Fragment example

### ISSUE THREAD

**Issue by aranda-adapptor** [electrode-io/electrode-native#368]
The documentation mentions that this is possible: `or host the MiniApp in a Fragment instead, then you'll need to use ElectrodeMiniAppActivity as a template to roll your own class.`.

Modern Android applications often use a single Activity and navigate between full-screen fragments, so it would be great if Electrode Native supported this and provided an example.

Another common use-case is for fragments to be shown below a menu bar and above a tab bar for global app navigation. Would there be any problems with having native UI for the menu and tab bar and a MiniApp hosted in the Fragment container?

**Comment by belemaire** [comment]
@aranda-adapptor 
We're currently working on a demo project around this and should be done soon. We will update this issue with links once done.
That being said, to answer your question, it is totally possible to mix native views and react native views on the same screen (in the same Activity). We believe this is a great use case for react native, to create custom simple or advanced UI components using react native and not only full screen MiniApps.

**Comment by aranda-adapptor** [comment]
@belemaire great, I look forward to seeing the sample / docs.

**Comment by abdyer** [comment]
@aranda-adapptor [Here's the link](https://github.com/electrode-io/ElectrodeNativeAndroidShowCaseApp) to the demo project. With this approach, you'll still need to extend `ElectrodeMiniAppFragment` in the main app to wire everything up as any `Fragments` added to the MiniApp will not make it into the container. Nevertheless, it's a step in the right direction. Hopefully we'll eventually have first class support for `Fragments` in MiniApps the same way we do for `Activities`

**Comment by deepueg** [comment]
@abdyer Thanks for pointing the sample app here. Yes, we are planning to add these base ElectrodeFragment and few other utilities to the generated container so devs can use them if needed or use it as a template for their implementations. I will make sure to update this thread when it is released.

**Comment by belemaire** [comment]
Moving this one to our backlog
