### ISSUE TITLE
Navigation API implementation in mini app MainActivity is missing from generated container

### ISSUE THREAD

**Issue by abdyer** [electrode-io/electrode-native#381]
After implementing a Navigation API similar to the [Movie application example](https://electrode.gitbooks.io/electrode-native/getting-started/getting-started.html) in one of my mini apps and generating the container AAR, my activity code is replaced with a minimal mini app activity class containing only a `getMiniAppName()` method. I also tried extending `ElectrodeMiniAppActivity` as mentioned in the tutorial, but had the same result.

How do I implement the Navigation API in my mini app activity and generate the container in such a way that the custom code is not removed?

Thanks in advance for the help! I'm eager to get this working as Electrode Native seems to solve a lot of the problems we've encountered integrating React Native into our existing native apps.

**Comment by deepueg** [comment]
@abdyer When a container is generated, the native code does not get packaged into the container.
Our assumption is that a miniapp will only have JS code inside it and no native code. Any native implementation would need to be added inside the native app that is going to include this container. 

For our tutorial, we used MovieListMiniApp as out native app for simplicity.  

If you want the navigation API implementation inside your app, please add the navigation API implementation to your native app to get a similar behavior as the Movie app. 

Please let us know if you are still facing issues.

**Comment by abdyer** [comment]
@deepueg Thanks for clarifying!
