### ISSUE TITLE
[mac] List of simulators not showing up on running ern run-ios or ern-android for ern version v0.10.1

### ISSUE THREAD

**Issue by kushan85** [electrode-io/electrode-native#383]
Using ern version v0.10.1, ern run-ios or ern run-android commands does not populate the list of simulators
Running on mac

**Comment by krunalsshah** [comment]
@kushan85  thanks for reporting this issue, please provide the detailed log 

`ERN_LOG_LEVEL=debug ern run-android` 
Also please let us know the node version your mac is configured to run. Thanks.

**Comment by kushan85** [comment]
| => node --version
v8.5.0

Logs when running the ERN_LOG_LEVEL=debug ern run-android

`This command is being run from the MovieListMiniApp MiniApp directory.
Initializing Runner
A React Native Packager is already running in a different process
Creating publisher for maven:file:///Users/kshah5/.m2/repository
containerGeneratorConfig is generated: {"platform":"android","publishers":[{"_name":"maven","_url":"file:///Users/kshah5/.m2/repository"}]}
Retrieving file:/Users/kshah5/checkouts/ElectrodeNativeTutorial/MovieListMiniApp
Creating an AndroidGenerator
Container will be published to file:///Users/kshah5/.m2/repository
Local Maven repository directory already exists
[=== Starting container hull filling ===]
Will inject: compile 'com.walmartlabs.ern:react-native:0.50.1'
[=== Adding plugin hook classes ===]
[=== Done adding plugin hook classes ===]
[GitManifest] Syncing https://github.com/electrode-io/electrode-native-manifest.git
[GitManifest] Fetching from origin master
Patching hull
Mustaching .npmignore
Mustaching build.gradle
Mustaching gradle/wrapper/gradle-wrapper.properties
Mustaching gradle.properties
Mustaching gradlew
Mustaching gradlew.bat
Mustaching lib/.npmignore
Mustaching lib/build.gradle
Mustaching lib/src/main/AndroidManifest.xml
Skipping mustaching of lib/src/main/assets/README.md
Skipping mustaching of lib/src/main/java/com/facebook/react/bridge/SafeActivityStarter.java
Mustaching lib/src/main/java/com/walmartlabs/ern/container/ElectrodeMiniAppActivity.java
Mustaching lib/src/main/java/com/walmartlabs/ern/container/ElectrodeReactActivityDelegate.java
Mustaching lib/src/main/java/com/walmartlabs/ern/container/ElectrodeReactContainer.java
Mustaching lib/src/main/java/com/walmartlabs/ern/container/README.md
Mustaching lib/src/main/java/com/walmartlabs/ern/container/miniapps/MiniAppsConfig.java
Mustaching lib/src/main/java/com/walmartlabs/ern/container/miniapps/README.md
Mustaching lib/src/main/java/com/walmartlabs/ern/container/plugins/README.md
Mustaching lib/src/main/res/README.md
Mustaching settings.gradle
Creating miniapp activities
Creating MovieListMiniAppActivity.java
[=== Completed container hull filling ===]
[=== Starting mini apps bundling ===]
Bundling miniapp(s) for Android
[=== Completed mini apps bundling ===]
[=== Starting build and publication ===]
[=== Completed build and publication of the module ===]
Published com.walmartlabs.ern:runner-ern-container:1.0.0
To file:///Users/kshah5/.m2/repository
✔ Generating Container locally
✔ Regenerating android Runner Configuration
? Choose Android emulator image
❯`

**Comment by kushan85** [comment]
run-ios logs

`| => ERN_LOG_LEVEL=debug ern run-ios
 ___ _        _               _       _  _      _   _
| __| |___ __| |_ _ _ ___  __| |___  | \| |__ _| |_(_)_ _____
| _|| / -_) _|  _| '_/ _ \/ _` / -_) | .` / _` |  _| \ V / -_)
|___|_\___\__|\__|_| \___/\__,_\___| |_|\_\__,_|\__|_|\_/\___|
[v0.10.1] [Cauldron: -NONE-]

This command is being run from the MovieListMiniApp MiniApp directory.
Initializing Runner
A React Native Packager is already running in a different process
containerGeneratorConfig is generated: {"platform":"ios","publishers":[]}
Retrieving file:/Users/kshah5/checkouts/ElectrodeNativeTutorial/MovieListMiniApp
Creating an IOSGenerator
Will not publish since there is no publisher provided to generator.
===iOS: building iOS plugin views
[=== Starting iOS framework project hull filling ===]
iOS: reading template files to be rendered for plugins
[GitManifest] Syncing https://github.com/electrode-io/electrode-native-manifest.git
[GitManifest] Fetching from origin master
Retrieving react-native
[runYarnCommand] Running /Users/kshah5/.ern/versions/0.10.1/node_modules/.bin/yarn add react-native@0.50.1 --ignore-engines --exact
warning react-native > connect@2.30.2: connect 2.x series is deprecated

warning "react-native@0.50.1" has unmet peer dependency "react@16.0.0".

[=== Completed framework generation ===]
[=== iOS: Adding plugin hook classes ===]
[=== iOS: Done adding plugin hook classes ===]
[=== Completed container hull filling ===]
[=== Starting mini apps bundling ===]
Bundling miniapp(s) for iOS
[=== Completed mini apps bundling ===]
=== ios: adding resources for miniapps
Container generation completed!
✔ Generating Container locally
✔ Regenerating ios Runner Configuration
CoreData: annotation:  Failed to load optimized model at path '/Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/Frameworks/InstrumentsPackaging.framework/Versions/A/Resources/XRPackageModel.momd/XRPackageModel 9.0.omo'
? Choose an iOS device (Use arrow keys)
❯ mac’s MacBook Pro udid: 134ACEBC.... version: 133 ---iOS: Finished add? Choose an iOS device`

**Comment by kushan85** [comment]
Let me know if you need any more information

**Comment by belemaire** [comment]
This is fixed in [v0.10.4](https://github.com/electrode-io/electrode-native/releases/tag/v0.10.4) of the platform.
