### ISSUE TITLE
build failed when init eletrode container (swift project)

### ISSUE THREAD

**Issue by Mactub07** [electrode-io/electrode-native#477]
hi, have a few questions 
- does electrode support integrating eletrode container in swift project?

my steps
1 created eletrode container;
2 created simple swift project;
3 added eletrode project to swift app (like in description);
4 while running project build failed with these mistakes http://prntscr.com/hym36x

additional comments : I didn't release container, just copy/pase container project inside native swift app;

http://prntscr.com/hym4uc

**Comment by deepueg** [comment]
@Mactub07 Have you followed the instructions detailed [here](https://electrode.gitbooks.io/electrode-native/content/platform-parts/container.html#adding-a-container-to-your-mobile-application])?

If not, please try this and let us know if you are still facing issues. Also, we will soon release a sample app for reference. I will keep this thread updated.

**Comment by deepueg** [comment]
Here is the sample iOS project for your reference: https://github.com/electrode-io/ElectrodeNativeiOSShowCaseApp.

Please let us know if you are still having issues getting the container inside your project.

**Comment by jomnius** [comment]
@Mactub07 you have copy & pasted Objective-C code into swift file. They are not compatible.

**Comment by belemaire** [comment]
Closing this one as it's been more than a month without activity. Feel free to reopen if needed.
