### ISSUE TITLE
Offer adding default local maven publisher when creating an Android native app

### ISSUE THREAD

**Issue by belemaire** [electrode-io/electrode-native#501]
In recent container/publisher refactoring, the default local maven publication disappeared for Android generated containers.

Publishers for a Container are configured in the Cauldron, there should be no exception to this rule. Problem with hardcoding a default local maven publisher is that there is no way to opt-out from it (unless we start adding specific command line options, which makes things more complex).

To make local maven publisher non hardcoded while keeping the simplicity and convenience of having such a publisher by default, we should prompt the user if Electrode Native should add a maven local publisher, at the time of creating the native application in the Cauldron.

So we should update the `cauldron add nativeapp` command, so that if adding a native app with `android` platform, the command shall prompt `Do you want to add a local maven publisher for this native application ? Y/n`. If `Y` (default) is selected, then the command will, once the native app entry is created in the Cauldron, invoke the Cauldron API to add a default local maven publisher to this native app in the Cauldron. If `n` is selected then we don't add a default local maven publisher.

This idea could be extended to other publisher types to ask at time of native app creation if the user want to add publisher (but this should be defined in another issue).

**Comment by belemaire** [comment]
Please do not start working on this one yet. Needs clarifications first to know if we really want to go down this road or opt for a different approach.

**Comment by jomnius** [comment]
Just a comment: please consider **how the command could be used from a script**. It would be useful, if you could provide true/false answers to prompts using command line parameters, otherwise the script automation might fail.

**Comment by belemaire** [comment]
Closing this one as it has been handled by https://github.com/electrode-io/electrode-native/pull/539
