### ISSUE TITLE
Error when attempting to "ern run-android"

### ISSUE THREAD

**Issue by luketowell** [electrode-io/electrode-native#504]
I am currently attempting to follow the tutorial. I have installed and created the MovieListMiniApp however when I cd into directory and use the command "ern run-android" I receive the following error:

-  "Generating Container locallyrunLocalContainerGen failed: TypeError: Cannot read property '1' of null"

The metro runner does open up and the react native packager is running on localhost:8081. the full error message looks like below:

[v0.11.3] [Cauldron: -NONE-]

√ Starting React Native packager
- Generating Container locallyrunLocalContainerGen failed: TypeError: Cannot read property '1' of null
× Cannot read property '1' of null
An error occurred: Cannot read property '1' of null`
I am attempting to do this on a windows 10 machine.

Have you experienced this issue before?

Thanks in advance.

Luke

**Comment by belemaire** [comment]
Hi @luketowell 

I will try it out later today from home on my Windows 10 PC and will give you feedback then (unfortunately we are working and testing mostly from Mac workstations at work).

**Comment by luketowell** [comment]
Hi @belemaire 
Thank you very much. 

Would you recommend that Mac should be used if you are mainly doing electrode-native / react-native development?

Kind regards,

Luke

**Comment by belemaire** [comment]
We don't recommend a specific platform for Electrode Native, that being said Mac makes more sense for cross platform mobile development as it is the only way to work on iOS applications.

Mac is also the platform we are using to develop Electrode Native. We don't have a large user base running Electrode Native on Windows and Linux (though we support these platforms), that's why there might be bugs left unnoticed :(

**Comment by belemaire** [comment]
@luketowell 
I was able to reproduce and fix. 
We won't release a patch version as we are looking into other Windows related issues and want to make sure that things work fine on Windows. 
Next version of Electrode Native (0.12.0) is scheduled for next Monday (29th) and will include the fix along with other Windows fixes.

**Comment by luketowell** [comment]
@belemaire, thanks very much. I will take your comment about cross platform mobile dev back to the higher ups. Cheers for the fix, fortunately I don't need to do anything till next Monday so it's all good.
