### ISSUE TITLE
create-api ignores --schemaPath parameter

### ISSUE THREAD

**Issue by abdyer** [electrode-io/electrode-native#509]
When running `ern create-api` with the `--schemaPath` parameter (relative path, absolute path, even with the schema file in the same directory) on ERN platform version 0.11.2, the resulting API project uses the default starter schema in each case. To workaround this, we copied our intended schema into the API project and ran `ern regen-api`.

Is there a non-obvious syntax for specifying the schema path for `ern create-api`?

**Comment by krunalsshah** [comment]
Thanks for reporting the issue. We will take a look at this.
