### ISSUE TITLE
How to build cross-platform miniApp with ERN runner, but without running it

### ISSUE THREAD

**Issue by jomnius** [electrode-io/electrode-native#522]
This could be just a documentation issue, but anyway here's my question:

I want to **setup CI/CD system** to verify that miniApp can a) be built and b) integrated into host application. Now focusing on first step and using jenkins pipeline.

PROBLEM: don't know what to do after running:

> ern create-container --version 1.0.0 --platform ios

Based on documentation the next step is always "ern run-ios", which seems to be doing BOTH build AND launching emulator. How would I do build-only? Without using custom xcodebuild step?

**Backup plan**: I guess I could setup Fastlane to do building and call that from Jenkinsfile. Is there any other possibilities? This one would require constant re-configuration and thus be pretty fragile. On the other hand I want to have CI/CD to minimize manual work and related mistakes.

**Comment by jomnius** [comment]
Status update: I'm now using xcodebuild

**Comment by clairewli** [comment]
@belemaire Do you mind sharing your insights into CI/CD?

**Comment by belemaire** [comment]
Closing this one as it's been a while it has been opened, @jomnius mentioned in a more recent issue that he would open a new issue to more clearly define the CI flow he wanted to achieve, we will then be able to give a more detailed answer to meet his requirements.
