### ISSUE TITLE
Publication cannot find react-native-code-push

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [electrode-io/electrode-native#534]
I think is problem is related to this:
https://github.com/electrode-io/electrode-native/blob/master/ern-local-cli/src/lib/publication.js#L318

I'm getting this error:
```
performCodePushOtaUpdate {e}
An error occurred: react-native-code-push plugin is not in native app !
```

But react-native-code-push is installed...
If I console.log(plugins), I get:
```
[ PackagePath {
    _fullPath: 'react-native@0.52.2',
    _basePath: 'react-native',
    _version: '0.52.2' },
  PackagePath {
    _fullPath: 'react-native-electropump-http-client-api-impl@1.1.0',
    _basePath: 'react-native-electropump-http-client-api-impl',
    _version: '1.1.0' },
  PackagePath {
    _fullPath: 'react-native-electrode-bridge@1.5.9',
    _basePath: 'react-native-electrode-bridge',
    _version: '1.5.9' },
  PackagePath {
    _fullPath: 'electropump-http-client-api@1.4.0',
    _basePath: 'electropump-http-client-api',
    _version: '1.4.0' },
  PackagePath {
    _fullPath: 'react-native-code-push@5.2.1',
    _basePath: 'react-native-code-push',
    _version: '5.2.1' } ]
```

There is no getter or property called `name` on a PackagePath object

**Comment by belemaire** [comment]
Thanks much for looking into this and pinpointing the root cause, that's a good catch.
Issued a fix, it will get shipped with patch version 0.12.1 of Electrode Native that we'll release today or tomorrow.

**Comment by rafaelcorreiapoli** [comment]
Have you guys ever thought about using some type system (like typescript or flow) for this project? It would avoid errors like this one :)

**Comment by belemaire** [comment]
@rafaelcorreiapoli 
We are making extensive use of flow throughout the code base but mostly typing function parameters and return types. We don't type arrow functions (parameters and return type) though we should definitely start doing it (would have caught this one).
