### ISSUE TITLE
'ern --version' short circuit other commands

### ISSUE THREAD

**Issue by belemaire** [electrode-io/electrode-native#537]
There is a problem with the way `ern --version` was implemented.

https://github.com/electrode-io/electrode-native/blob/master/ern-local-cli/src/index.js#L56

The problem is that the code sits at the top level and just looks if there is `--version` in the command option. This actually short circuit any command that is having a `--version` option (`create-container` for example). If running `ern create-container --version 1.0.0 ...` then the command will not be executed, it will instead execute the code to display the electrode native version.

`ern --version` should therefore be implemented in a different way that will not short circuit commands that are using a `--version` as part of their option list.

**Comment by jomnius** [comment]
Great timing, I was wondering about that yesterday :)
