### ISSUE TITLE
cauldron update dependency command downgrades native dependency package version

### ISSUE THREAD

**Issue by clairewli** [electrode-io/electrode-native#559]
When I try to update multiple mini-app versions which have native-dependencies lower than the current native dependencies, cauldron native dependencies get overwritten by a lower version dependency. For example, my mini-app A, B and C both using native dependency react-native-something-api@0.0.5, whereas inside cauldron it's react-native-something-api@0.0.10. Now when I do ern cauldron update miniapps, my cauldron gets overwritten with react-native-api@0.0.5 when it should be 0.0.10

**Comment by belemaire** [comment]
Related to https://github.com/electrode-io/electrode-native/issues/498

**Comment by belemaire** [comment]
Seems like the bug is coming from [this LOC](https://github.com/electrode-io/electrode-native/blob/master/ern-core/src/MiniApp.js#L451). 
Doing string comparison for versions, leading to `'0.010' < '0.05'` and other buggy side effects.
Should use `semver` lib for version comparisons.
