### ISSUE TITLE
cauldron update dependency command downgrades native dependency package version

### ISSUE THREAD

**Issue by krunalsshah** [electrode-io/electrode-native#569]
For Example 
Current State

```
 "nativeDeps": [
react-native-maps@0.13.1
]
```
Run command `ern cauldron update miniapps <mini-app>`, where `mini-app`'s package.json  has entry `react-native-maps@0.13.0` 
After
```
 "nativeDeps": [
react-native-maps@0.13.0
]
```

Solution : Do not change if the version current is greater than `mini-app` package version

**Comment by belemaire** [comment]
Woops sorry, though @clairewli reported issue was different, but in fact it's the same :(
Closing as diplicate of https://github.com/electrode-io/electrode-native/issues/559
