### ISSUE TITLE
Upgrading cauldron schema erroring out 

### ISSUE THREAD

**Issue by chrisdojo** [electrode-io/electrode-native#589]
I created a cauldron file in electrode native version v0.11.3, after upgrading to v0.13.0 I tried to use ern cauldron upgrade but ran into this issue:

```
[v0.13.0] [Cauldron: dojo-cauldron]

Upgrading Cauldron schema from v0.0.0 to v1.0.0
Something went wrong : TypeError: Cannot create property 'jsApiImpls' on string 'c'
An error occurred: Cannot create property 'jsApiImpls' on string 'c'
```

The cauldron commands like update were working before the upgrade

**Comment by belemaire** [comment]
So it seems like the `cauldron upgrade` command failed for some reason :( 
Is your cauldron GitHub repository public ? If so, could you please give use the URL to your Cauldron ? Otherwise could you just copy paste your whole Cauldron content here ? 
This way we'll be able to reproduce and look into what's the problem (and fix it if that's a bug).

**Comment by chrisdojo** [comment]
Thanks for the reply.  Here is the cauldron file:

`
{
  "nativeApps": [
    {
      "name": "ClassDojo",
      "platforms": [
        {
          "name": "android",
          "versions": [
            {
              "name": "0.0.1",
              "ernPlatformVersion": "0.11.3",
              "isReleased": false,
              "binary": null,
              "yarnLocks": {
                "container": "8ba76ebfb25e82b4a6b41061c197a6b562202994"
              },
              "nativeDeps": [
                "react-native-ernnavigation-api@0.0.4",
                "react-native@0.51.0",
                "react-native-code-push@5.2.1",
                "react-native-electrode-bridge@1.5.9"
              ],
              "miniApps": {
                "container": [
                  "@classdojo/android-sales-page-miniapp@0.0.11"
                ]
              },
              "codePush": {
                "appName": "chris.k-1/AndroidSalesPageMiniApp"
              },
              "containerVersion": "1.0.10"
            }
          ],
          "config": {
            "codePush": {
              "deployments": [
                {
                  "name": "Dev"
                },
                {
                  "name": "Staging"
                }
              ]
            },
            "containerGenerator": {
              "containerVersion": "1.0.10",
              "publishers": [
                {
                  "name": "maven",
                  "url": "https://artifactory.classdojo.com/artifactory/libs-release-local"
                },
                {
                  "name": "github",
                  "url": "git@github.com:classdojo/AndroidSalesPageMiniApp.git"
                }
              ]
            }
          }
        }
      ]
    }
  ]
}
`

Also on a side note, this issue came about when trying to use this cauldron file on a coworker's computer, is there an easy way to associate a cauldron file with a person's current electrode setup?  We were looking for some sort of ern cauldron use command but didn't see anything like that in the documentation.

Thanks again
