### ISSUE TITLE
Update android runner project build.gradle with custom repositories

### ISSUE THREAD

**Issue by deepueg** [electrode-io/electrode-native#593]
Currently, if you have a native plugin that adds some additional custom repos(in the manifest) to download its dependencies we still need to update the runner project manually with those repo URLs.  The manifest URLs are used while a container is generated but not for the runner project's build.gradle.  It would be nice to add these repo URLs to the runner project to avoid a manual update.

**Comment by belemaire** [comment]
@deepueg 
Could you provide a bit more details regarding this one if it still is needed ? 
Also should we plan implementation for next release (0.16.0) or postpone it to a later release ?

**Comment by deepueg** [comment]
@belemaire sorry, I missed that. Added now.

**Comment by belemaire** [comment]
@deepueg Moving this one to v0.17.0 (next) release

**Comment by belemaire** [comment]
Moving this one to backlog
