### ISSUE TITLE
Installing non-released platform version 0.13.2 from branch

### ISSUE THREAD

**Issue by jomnius** [electrode-io/electrode-native#608]
Command `ern platform list` says version 0.13.2 is available. When looking at [master branch releases](https://github.com/electrode-io/electrode-native/releases), the latest release is version 0.13.1. 

However I was able to find the 0.13.2 from  [v0.13 branch](https://github.com/electrode-io/electrode-native/tree/v0.13) as a commit message. It's not a tag, just a commit message. In a branch.

I was able to install non-released platform 0.13.2 from a branch using command `ern platform use 0.13.2`. Or maybe it was released and someone forgot to make (automate) git release at the same time? And merge to master branch? In any case I have no idea what sources I'm now using :)

**BUG:**

Please make it obvious what ERN source code belongs to what release.

**Comment by belemaire** [comment]
Forgot to tag the branch. More things to automate indeed.

**Comment by belemaire** [comment]
Tagging done.
