### ISSUE TITLE
Typo in ern cauldron add publisher

### ISSUE THREAD

**Issue by inturbidus** [electrode-io/electrode-native#621]
Run: ern cauldron add publisher

Returns:
An error occurred: Please provide a publisher option (publisher --mavenUrl or --gitHubUrl)

Should be:
An error occurred: Please provide a publisher option (publisher --mavenUrl or --githubUrl)

Replace gitHubUrl with githubUrl to prevent "Unknown argument: gitHubUrl"

**Comment by krunalsshah** [comment]
thanks for reporting the issue @inturbidus We have created a PR to fix it.
