### ISSUE TITLE
Docs: PR at Bridge repo

### ISSUE THREAD

**Issue by jomnius** [electrode-io/electrode-native#626]
Just a heads-up that I made a minor PR at bridge repo (readme file), which was referenced from Electrode Native documentation. Not sure, if you would notice it otherwise. Sorry :)

https://github.com/electrode-io/react-native-electrode-bridge/pull/30

This issue can be closed.

**Comment by belemaire** [comment]
Merged. Thanks for the ping, it seems like none of us had git notifications enabled for the bridge repo :S
