### ISSUE TITLE
ern create-container took lot of time to fail for wrong parameter with no feedback

### ISSUE THREAD

**Issue by madhanganesh** [electrode-io/electrode-native#627]
I am in ern 0.13.2. I ran

ern create-container -out ~/temp/erncontainer3 -p android

with a wrong parameter for out (one hyphen instead of two). This command run for long time (~ 5 mins) with a message the container is created. But there were no files under the given directory. had to try this multiple time with no result. It would help a lot if parameters are validated at the start and reported with helpful message.

the out I got for a wrong parameter is:
✔ Validity checks have passed
? Choose a non released native application version for which to generate container gifenpoc:android:0.0.1
✔ Validity checks have passed
⠸ Creating Container for gifenpoc:android:0.0.1 from Cauldronreact-native does not have any injection configuration for android platform
⠼ Creating Container for gifenpoc:android:0.0.1 from CauldronSkipping react-native as it does not have an Android configuration
✔ Creating Container for gifenpoc:android:0.0.1 from Cauldron

**Comment by belemaire** [comment]
@madhanganesh 
`ern create-container -out ~/temp/erncontainer3 -p android` should fail immediately.
I tried it on Mac and Windows, the result is the same, the command does not even run. It fails with :

```
Unknown arguments: o, u, t
```

I am not sure why you are running in this issue :(

**Comment by belemaire** [comment]
This issue was closed as there was no follow up from author for at least 2 weeks.
Feel free to reopen issue if needed.
