### ISSUE TITLE
ern cauldron add publisher

### ISSUE THREAD

**Issue by clairewli** [electrode-io/electrode-native#632]
When using `ern cauldron add publisher --githubUrl=git@mygithub.com:user/container.git` command to setup GithubUrl and only pass --githubUrl flag without passing -d flag, the platform will prompt the user to choose a platform. Once a platform is chose, in my case it's `ios`, an error is thrown `An error occurred: Looks like there are no application defined in the cauldron for ios`.

**Comment by belemaire** [comment]
Fixed by https://github.com/electrode-io/electrode-native/pull/634
