### ISSUE TITLE
Native and mini app integration using Container

### ISSUE THREAD

**Issue by kamleshgit** [electrode-io/electrode-native#636]
Hello,

I was able to add cauldron to my git repository and also added my native app to cauldron using **ern cauldron add nativeapp MyApp:android:0.0.1** command. I can see a new cauldron.jason file there in repository.
Now I need to understand how to CREATE Container for my mini app that I did creat earlier so that I can use the ARR files to get my mini app integrated with my Native app.

My main questions are:
1. how to use the cauldron.json file
2. How to generate containers 
3. and then finally how to use it to integrate my mini app with y native app?

Can some one help please?

Thanks
Kamlesh

**Comment by deepueg** [comment]
@kamleshgit Please see my answer for https://github.com/electrode-io/electrode-native/issues/637. Let us know if you are still facing issues.

**Comment by belemaire** [comment]
This issue was closed as there was no follow up from author for at least 2 weeks.
Feel free to reopen issue if needed.
