### ISSUE TITLE
container problem

### ISSUE THREAD

**Issue by Ashutosh21Nigam** [electrode-io/electrode-native#637]
i have create one mini app  and update code . i have create one native app . i want to add  mini app to native app so am create github repository and add project use this command "ern cauldron repo add electro https://github.com/Ashutosh21Nigam/electro.git" to repository . this is successfully added  and add native app to repository use this command "ern cauldron add nativeapp MyNativeApp:android:1.0"  this is successfully added and create cauldron.json . 
so now i face a problem how to create container and what to do for cauldron.json file.
please provide solution in details how to add mini app to native  app  and i have cauldron.json file but not understand how to create  container and further steps .

**Comment by deepueg** [comment]
@Ashutosh21Nigam  Here are some breakdowns of what you can do to create a container. 
- Good that you already have a cauldron
- Assuming you have a miniapp, you may need to publish the miniapp to npm or GitHub.
- Add publishers to your cauldron: https://electrode.gitbooks.io/electrode-native/content/cli/cauldron/add/publisher.html
- Add miniapp to your native app in cauldron: https://electrode.gitbooks.io/electrode-native/content/cli/cauldron/add/miniapps.html

This should generate a container and publish to your publishers. 

Let us know if this helps you proceed or if you still have questions.

**Comment by epsilonium** [comment]
Hi Deep,

I am sorry for the delayed response. I really appreciate the help you provided, Thank you :).
Actually I am looking to generate container locally and when I use ern create container command it do not work and give me an error "This command is not recognized" Do you know what I may have been doing wrong?

Thanks

**Comment by jomnius** [comment]
@kamlesheps Just to be sure, please verify that there is dash between "create" and "container" parts == it's just ONE word:

```bash
ern create-container --descriptor MyNativeApp:android:1.0
```

Otherwise you can check available commands at https://electrode.gitbooks.io/electrode-native/
