### ISSUE TITLE
how to integrate mini app to native app

### ISSUE THREAD

**Issue by Ashutosh21Nigam** [electrode-io/electrode-native#640]
Hello ,
I was able to add publisher with use this command "ern cauldron add publisher --githubUrl=<url>" thats gives response github publisher was successfully added!
so now please tell  me what my next steps 
My main question is :  how  to integrate my mini app with native app?

**Comment by belemaire** [comment]
@Ashutosh21Nigam 
Please see reference documentation on the [Container](https://electrode.gitbooks.io/electrode-native/platform-parts/container.html). This contains some details about adding a Container to an existing mobile application. 
Let us know in case you are not able to proceed by just using this reference page, always looking for ways to improve documentation if it's unclear.

**Comment by belemaire** [comment]
This issue was closed as there was no follow up from author for at least 2 weeks.
Feel free to reopen issue if needed.

**Comment by nagender04031989** [comment]
@belemaire  - I'm new to electrode native and trying to create the mini apps. Just went through the tutorial for creating MovieListMiniApps which using another miniapp via NavigationAPI. I also created two different miniapps and I want to know the way to connect these two miniapps without Navigation API. Thanks.
