### ISSUE TITLE
error for using command 

### ISSUE THREAD

**Issue by Ashutosh21Nigam** [electrode-io/electrode-native#641]
Hello,
when  i use this command " ern run-android --miniapps moviedetailsminiapp --mainMiniAppName MovieListMiniApp "  generate error below 👎 

C:\ElectrodeNativeTutorial\ElectrodeNative\MyMiniApp\MovieListMiniApp>ern run-android --miniapps moviedetailsminiapp --mainMiniAppName MovieListMiniApp
 ___ _        _               _       _  _      _   _
| __| |___ __| |_ _ _ ___  __| |___  | \| |__ _| |_(_)_ _____
| _|| / -_) _|  _| '_/ _ \/ _` / -_) | .` / _` |  _| \ V / -_)
|___|_\___\__|\__|_| \___/\__,_\___| |_|\_\__,_|\__|_|\_/\___|
[v0.12.0] [Cauldron: electro]

All extra MiniApps will be included in the Runner container along with MovieListMiniApp
runLocalContainerGen failed: Error: The following native dependencies are not using the same version: react-native
An error occurred: The following native dependencies are not using the same version: react-native

please help me how to fixed it.....

**Comment by belemaire** [comment]
Hi @Ashutosh21Nigam 
The error indicates that the MiniApps you are trying to bundle together for `run-android` are not using the same react-native version. It is not possible to create a Container that contains MiniApps running different versions of React Native.
`moviedetailsminiapp` as of today is using `react-native@0.53` and `react@16.2.0` (can be seen by running `npm info moviedetailsminiapp dependencies`).
It seems like you are still on `v0.12.0` of Electrode Native. This version was targeting react-native `0.52.2` so I would guess that your MovieListMiniApp is still on this version (whereas our latest publication of movidetailsminiapp is using `0.53.0`).
Two different ways to solve this, up to you :

1) Upgrade your Electrode Native version and MiniApp dependencies versions
  a. Run `ern platform use 0.14.2` (to install and switch to the latest version of Electrode Native)
  b. From your `MovieListMiniApp` directory, run `ern upgrade-miniapp` (this will update the version of react-native used by your MiniApp to match the one used by latest platform version (0.53.0)
  c. At this point, you can the same command you were trying to run. Your MiniApp will be on 0.53.0 of react-native and the latest moviedetailsminiapp we published (0.0.10) is also on 0.53.0 so no more problem.

OR

2) Don't upgrade Electrode Native version but use proper version of moviedetailsminiapp
Just keep everything as such, but just replace in your command, the `--miniapps moviedetailsminiapp` by `--miniapps moviedetailsminiapp@0.0.9`. Version 0.0.9 of moviedetails MiniApp is using 0.52.2 of react-native, and will therefore be compatible with your current MovieListMiniApp.

**Comment by belemaire** [comment]
This issue was closed as there was no follow up from author for at least 2 weeks.
Feel free to reopen issue if needed.
