### ISSUE TITLE
Geofence location in electrode native

### ISSUE THREAD

**Issue by Ashutosh21Nigam** [electrode-io/electrode-native#642]
Hello,
i have a problem how can i deal with geo fence location in electrode native and please help me what is the plugin for geo fence using electrode native . 
there is an error while using react native plugin for geofence . this error is given below 👎 
using this plugin : " npm install react-native-background-geolocation --save " than install but while using " ern run-android " command then i get error below.

C:\ElectrodeNativeTutorial\ElectrodeNative\MyMiniApp\MovieListMiniApp>ern run-android
 ___ _        _               _       _  _      _   _
| __| |___ __| |_ _ _ ___  __| |___  | \| |__ _| |_(_)_ _____
| _|| / -_) _|  _| '_/ _ \/ _` / -_) | .` / _` |  _| \ V / -_)
|___|_\___\__|\__|_| \___/\__,_\___| |_|\_\__,_|\__|_|\_/\___|
[v0.12.0] [Cauldron: electro]

√ Starting React Native packager
- Generating Containerreact-native does not have any injection configuration for android platform
Skipping react-native as it does not have an Android configuration
√ Generating Container
C:\Users\ADMIN\AppData\Local\Temp\tmp-9236XUE8vUdQ4x2N C:\Users\ADMIN\AppData\Local\Temp\tmp-9236tlIPFANNT8zh
C:\Users\ADMIN\AppData\Local\Temp\tmp-9236tlIPFANNT8zh
√ Regenerating android Runner Configuration
× Command failed: gradlew installDebug

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:generateDebugBuildConfig'.
> java.io.IOException: Could not delete path 'C:\ElectrodeNativeTutorial\ElectrodeNative\MyMiniApp\MovieListMiniApp\android\app\build\generated\source\buildConfig\debug\com\walmartlabs'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s

An error occurred: Command failed: gradlew installDebug

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:generateDebugBuildConfig'.
> java.io.IOException: Could not delete path 'C:\ElectrodeNativeTutorial\ElectrodeNative\MyMiniApp\MovieListMiniApp\android\app\build\generated\source\buildConfig\debug\com\walmartlabs'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s

please help me how to add geofence in my mini app project.

**Comment by belemaire** [comment]
@Ashutosh21Nigam 
I am not aware of any geo fencing library built in react-native itself.
Are you using a third party native module (plugin) in your MiniApp to achieve geo fencing ?
If so, you will need to create a [plugin configuration in the Electrode Native manifest](https://github.com/electrode-io/electrode-native-manifest/tree/master/plugins/ern_v0.13.0%2B) to properly add support for this plugin in Electrode Native, if no configuration already exist for this plugin.
Please clairfy, thanks.

**Comment by belemaire** [comment]
This issue was closed as there was no follow up from author for at least 2 weeks.
Feel free to reopen issue if needed.
