### ISSUE TITLE
Cauldron definition is system-wide value

### ISSUE THREAD

**Issue by jomnius** [electrode-io/electrode-native#665]
Works as designed, so not really a bug. Just wanted to report this to you:

If you have a jenkins CI/CD system working with more than one Electrode Native application, you might get into a race condition, where definition of cauldron changes between defining your cauldron and creating the container from it:

> ✖ MyDemo:ios:0.0.1 descriptor does not exist in Cauldron.
You cannot create a container for a non existin native application version.

**Solution**: make sure react native apps are handled in separate jenkins slave machines... which is kind of understandable, but not optimal. The real problem will be that in our system only master has access rights to make releases (for reasons I cannot remember) and then we're back at potential race condition problem.

Personally I would prefer e.g. some local file based build configuration...

But I'm not that far yet... you promised elsewhere a CI/CD tutorial, looking forward to that. In the meanwhile I'm learning a ton about jenkins and GitHub configurations.

Btw related part of build script:

```bash
# === Setup ERN
ern platform use 0.12.2
ern cauldron repo remove my-app-cauldron
ern cauldron repo add my-app-cauldron git@github.compa.ny:Project/my-app-cauldron.git --current true

# === Setup project
ern create-container --descriptor MyDemo:android:0.0.1
```

**Comment by jomnius** [comment]
**SOLVED, this ticket can be closed:**

I was reading some of your latest commits related to CI testing and by total accident found out that we can define a local .ernrc file, which will overwrite global settings from ~/.ern/.ernrc file !!!

I didn't know that such file even existed and even less that I can override the settings by using a local file !!! Happy (happier) again, thanx !!!

**Comment by jomnius** [comment]
Hmm, part of a solution.

**Comment by belemaire** [comment]
@jomnius 
Yes you can define a local `.ernrc` file. That being said I remember we did this implementation a loooong while ago, and we are not using such local `.ernrc` (and I don't think it's widely tested). 
It should properly work, but if you notice any issues let us know !

Can I close this ticket or not ? 
Your 'before latest' comment says it can be closed but your latest comment seems to indicate the door is still open ;)

**Comment by jomnius** [comment]
I tested defining new cauldron alias and the definition went into local .ernrc file, as expected. However I did not try to break the system by defining same alias with different urls and trying to create two cauldrons from them at the same time etc. edge cases.

This ticket can be closed. If I bump into same problem again, I'll create a new ticket. Thanx!

**Comment by belemaire** [comment]
ok thanks.
