### ISSUE TITLE
Problem running on kubuntu 17.10

### ISSUE THREAD

**Issue by jadolg** [electrode-io/electrode-native#690]
Hi electrode-native team. I've been trying to start electrode-native app following the getting started guide on my kubuntu 17.10. Everything installs fine and doesn't break until I run `ern run-android`. Here is my output:

```
akiel@alucy:~/Desktop/ElectrodeNativeTutorial/ASmallAppMiniApp$ ern run-android
 ___ _        _               _       _  _      _   _         
| __| |___ __| |_ _ _ ___  __| |___  | \| |__ _| |_(_)_ _____ 
| _|| / -_) _|  _| '_/ _ \/ _` / -_) | .` / _` |  _| \ V / -_)
|___|_\___\__|\__|_| \___/\__,_\___| |_|\_\__,_|\__|_|\_/\___|
[v0.15.0] [Cauldron: -NONE-]

✔ Starting React Native packager
(node:25512) UnhandledPromiseRejectionWarning: Error: spawn gnome-terminal ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
(node:25512) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:25512) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
⠋ Generating Containerreact-native does not have any injection configuration for android platform
Skipping react-native as it does not have an Android configuration
✔ Generating Container
/tmp/tmp-25512vQKP8tBBZ7TV /tmp/tmp-25512O7cZEdq0FiYY
/tmp/tmp-25512O7cZEdq0FiYY
An error occurred: Command failed: ./gradlew lib:uploadArchives
Exception in thread "main" java.lang.RuntimeException: java.util.zip.ZipException: error in opening zip file
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:78)
        at org.gradle.wrapper.Install.createDist(Install.java:44)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:126)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:58)
Caused by: java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:225)
        at java.util.zip.ZipFile.<init>(ZipFile.java:155)
        at java.util.zip.ZipFile.<init>(ZipFile.java:169)
        at org.gradle.wrapper.Install.unzip(Install.java:157)
        at org.gradle.wrapper.Install.access$400(Install.java:26)
        at org.gradle.wrapper.Install$1.call(Install.java:67)
        at org.gradle.wrapper.Install$1.call(Install.java:44)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
        ... 3 more
```

```
$ node -v
v8.10.0
```
```
$ npm -v
5.6.0
```
```
$ yarn -v
1.5.1
```
```
$ java -version
openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-0ubuntu0.17.10.2-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)
```
```
$ gradle -v

------------------------------------------------------------
Gradle 4.6
------------------------------------------------------------

Build time:   2018-02-28 13:36:36 UTC
Revision:     8fa6ce7945b640e6168488e4417f9bb96e4ab46c

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          1.8.0_151 (Oracle Corporation 25.151-b12)
OS:           Linux 4.13.0-37-generic amd64
```

Android SDK and Gradle are both in PATH and variables ANDROID_SDK, ANDROID_HOME and GRADLE_HOME are defined. Is there something I'm missing?

**Comment by belemaire** [comment]
Thanks for reporting this.

It seems like there are two issues here :

1. `Error: spawn gnome-terminal ENOENT`
We are assuming `gnome-terminal` is available in the linux env. While it's shipped with Ubuntu, I'm not sure about kubunutu, but it seems like it's not there in your env. This is needed for the local react native packager to be started as we are spawning it in a new terminal window. Might have to figure out a best way to do that, meanwhile to fix this issue you might want to install `gnome-terminal`.

2. `An error occurred: Command failed: ./gradlew lib:uploadArchives
Exception in thread "main" java.lang.RuntimeException: java.util.zip.ZipException: error in opening zip file`
Seems like there is something going on with gradle build. zip might be related to the gradle distribution url (it's a zip), but not sure because the stack trace is not very explicit in regards to the root cause.
Will have to try to repro later on today on my Linux machine (Ubuntu), maybe we introduced some kind of regression for Linux in a recent version, will keep you posted.

**Comment by jadolg** [comment]
Thanks for your quick response :) Installing gnome-terminal solved the first problem. The second one persists. Question: Does it download a Gradle distribution? I already have gradle setted in my environment and it works perfect with AndroidStudio.

**Comment by belemaire** [comment]
Yes it does download a gradle distribution via the [gradle wrapper](https://docs.gradle.org/current/userguide/gradle_wrapper.html) (this is common and recommended practice for Android projects as it guarantees consistency regarding the version of gradle used for a given project and does not require user to have to install gradle by him/herself).

Distro url is stored in this [gradle-wrapper.properties](https://github.com/electrode-io/electrode-native/blob/master/ern-container-gen/src/generators/android/hull/gradle/wrapper/gradle-wrapper.properties#L6) file of the Container.

Quickly googling, I found out a somewhat [similar issue](https://github.com/ionic-team/ionic-cli/issues/2787) on another project, it seems like by deleting the cached zip file solve the issue. 
Not sure about the path though, they mention `/home/shared/.gradle/wrapper/dists/` but it might also be `~/.gradle/wrapper/dists`. The directory to remove would be `gradle-4.1-all` as this is the one that gets downloaded for Container build, so maybe this one is corrupted somehow on your machine.

Could you please take a look and let me know.

**Comment by jadolg** [comment]
If I uncompress this gradle version here should it work or will try to download it again?

**Comment by belemaire** [comment]
You shouldn't uncompress it manually, it will try to download it again if the `gradle-4.1-all` directory is missing.

**Comment by jadolg** [comment]
Cuba is a difficult place to be downloading files all the time. Well, I deleted gradle and run it again and now I'm getting something else:
```
ern run-android
 ___ _        _               _       _  _      _   _         
| __| |___ __| |_ _ _ ___  __| |___  | \| |__ _| |_(_)_ _____ 
| _|| / -_) _|  _| '_/ _ \/ _` / -_) | .` / _` |  _| \ V / -_)
|___|_\___\__|\__|_| \___/\__,_\___| |_|\_\__,_|\__|_|\_/\___|
[v0.15.0] [Cauldron: -NONE-]

✔ Starting React Native packager
⠋ Generating Containerreact-native does not have any injection configuration for android platform
Skipping react-native as it does not have an Android configuration
✔ Generating Container
/tmp/tmp-3114977gqOlEDGCrv /tmp/tmp-31149qHJy0t5kM236
/tmp/tmp-31149qHJy0t5kM236
An error occurred: Command failed: ./gradlew lib:uploadArchives

FAILURE: Build failed with an exception.

* Where:
Build file '/tmp/tmp-3114977gqOlEDGCrv/lib/build.gradle' line: 1

* What went wrong:
A problem occurred evaluating project ':lib'.
> Failed to apply plugin [id 'com.android.library']
   > Could not create plugin of type 'LibraryPlugin'.
      > com/android/builder/core/ErrorReporter

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 9m 34s
```

**Comment by jadolg** [comment]
Any ideas? Do you have any IRC/Slack/Gitter we can use to chat? It is being a real setback for me not being able to get the project running and this is the only way I know to talk to the community.

**Comment by jadolg** [comment]
Well, it's already solved. I deleted the Gradle cache and tried to run again. It downloaded a lot of packages and started working. Seems that some dependencies were broken when downloading. Thanks a lot for your help.
