### ISSUE TITLE
Publishing a new container deletes the miniapp source code

### ISSUE THREAD

**Issue by dharmin007** [electrode-io/electrode-native#694]
Whenever I publish a container, the miniapp source code (App.js) gets deleted. Have I configured something incorrectly or could this possibly be a bug? 
![screen shot 2018-03-21 at 10 12 33 am](https://user-images.githubusercontent.com/82306/37725770-f7b3b81c-2cf0-11e8-91ea-38a9744fe584.png)

**Comment by belemaire** [comment]
@dharmin007 
There shouldn't be an `App.js` in the Container. In term of JavaScript, what the container contains is just the final JavaScript bundle (MiniApp.jsbundle for iOS and index.android.bundle for Android). Original JS MiniApp(s) code is not shipped with the Container, so I don't really know why you see this `App.js`, it shouldn't have been there in the first place anyway.
Could you share a screenshot of your Container GitHub repo ? (top level, to see how the file structure looks like)

**Comment by dharmin007** [comment]
@belemaire Thanks for the quick response! The top level of the container repo looks like this: 
![screen shot 2018-03-21 at 10 47 57 am](https://user-images.githubusercontent.com/82306/37727579-72b9c41c-2cf5-11e8-8016-158ce757610e.png)

**Comment by dharmin007** [comment]
I am guessing this is happening due to specifying the same repo that I have for the miniapp also as the publisher under container generation?

**Comment by belemaire** [comment]
@dharmin007 
Yes if you are specifying an output directory explicitly for the Container to be generated in (with the `--outDir` option of `create-container`) you should use an empty directory, not one containing your MiniApp.
