### ISSUE TITLE
[mac] List of iPads simulators not showing up on running ern run-ios on version v0.14.3

### ISSUE THREAD

**Issue by RandyHBH** [electrode-io/electrode-native#700]
Hi guys, I was trying to try to run the app using an iPad simulator but on the list, only appears iPhones. Am I missing something? 
Can anyone help me?

**Comment by belemaire** [comment]
@RandyHBH
Thanks for reporting. It seems like we filter the device list to only keep iPhones for some reason. This happens at this [LOC](https://github.com/electrode-io/electrode-native/blob/b2c0cbd652e244405d75eeb41dca4f3e43a46170/ern-core/src/ios.js#L27).
We will fix this to also show iPad devices.
Meanwhile, as the `run-ios` command won't show iPad, what you can do is use `run-ios` until it ask you for the device on which to launch, then just kill the command and open the Runner project in XCode directly (in the `ios` folder of the MiniApp you're running it from), from XCode you can just build and run the project on iPad as any other applicative project.

@clairewli Could you please look into this one at your convenience. We will release it with 0.17.0.

**Comment by belemaire** [comment]
Moving this one to our backlog
