### ISSUE TITLE
How should I create my first cauldron? 

### ISSUE THREAD

**Issue by amloelxer** [electrode-io/electrode-native#702]
Apologies if I should ask this somewhere else, but I can't find this anywhere in the docs. The last couple months I've been using `ern run-ios` to test/ran my mini app by itself for testing/development. I'm getting to the point where I'm getting ready to add my mini app to our native application, but I'm not sure how I generate the first cauldron. Do I start with a blank github repository, set the cauldron url, and then start adding things to it and the JSON is auto generated? Or do I start with a blank/ filled in json document add it manually to the repo? If this is not already in the docs, it definitely might be a worthy add as I can't find it in the `Cauldron` section nor on the `Electrode Native Workflow` page.

**Comment by krunalsshah** [comment]
Thanks @amloelxer for reaching out  
Here's the summary of steps 
- Create new mobile application versions in the cauldron using the Electrode Native `ern cauldron add nativeapp` command.
- Add, Remove, and Update MiniApps for a target in-development mobile application version (shipped in a container) using the `ern cauldron [add/del/update] miniapps` commands.
- Add, Remove, and Update native dependencies for target in-development mobile application version using the ern cauldron [add/del/update] dependencies commands (shipped in a container)
- After the `.aar` file or `framework` project is created integrate that with the Native App

You may find instructions for setting up cauldron here 
https://electrode.gitbooks.io/electrode-native/content/platform-parts/cauldron.html

You may find container initialization & related information here 
https://electrode.gitbooks.io/electrode-native/content/platform-parts/container.html#initializing-a-container

Please use the above as a reference point & feel free to ask questions.

**Comment by amloelxer** [comment]
@krunalsshah thanks for reaching out. I'm aware of all these steps but my question has to do with the initial creation of the actual cauldron file. When I do `ern cauldron add nativeapp` it will tell me 
`There is no active Cauldron. A Cauldron must be active in order to use this command`. Once I make a place for my cauldron (i.e github) will the cauldron file autogenerate with `ern cauldron add nativeapp?` Or do I have to begin its initial creation myself?

**Comment by krunalsshah** [comment]
Ah K.

run the command 
`ern cauldron repo add <cauldron-alias> <cauldron-url>`
where you can use `github` url for `<cauldron-url>` & use any alias name to reference it. After which 
`ern cauldron add nativeapp <descriptor>` will use the `cauldron-url` & make the commits, this should be transparent to the end user.

**Comment by amloelxer** [comment]
@krunalsshah ahh got it. Thank you!
