### ISSUE TITLE
Use nexus for caching purposes

### ISSUE THREAD

**Issue by jadolg** [electrode-io/electrode-native#709]
Hi electrode-native team. I would like to use Nexus to provide a cache for the packages I have to download to use electrode. I'm already using it for npm using .npmrc file in my home folder but would like to set it up for maven dependencies too. Is there a way to do it? Downloading all these packages is very time-consuming for me since I'm in a restricted bandwidth environment.

**Comment by krunalsshah** [comment]
@jadolg thanks for reaching out.
w.r.t `maven dependencies` being pulling from local cache, can't you just take advantage of `.m2` directory at root of you `user` directory?

If your react native project is created using `ern create-miniapp <appName>`, it's already set up to read the packages from `mavenLocal` 
https://github.com/electrode-io/ColorPickerMiniApp/blob/master/android/build.gradle#L18 

Does that answer your question?

Unless your goal is to set up [Nexus](https://www.sonatype.com/nexus-repository-sonatype) locally

**Comment by jadolg** [comment]
I work with a team of engineers in a very restricted bandwidth environment. We are trying to cache all dependencies in our local nexus so we don't have to spend 20+ minutes downloading files from the internet every time we have to set up our environment. Every time gradle fails to download some file and as a result we have broken dependencies is a nightmare to redownload all files again.

**Comment by krunalsshah** [comment]
@jadolg if you have yet not tried point the root `build.gradle` file to point to local/provate `nexus` instance

An entry like 
`maven { url 'http://localhost:8081/nexus/content/groups/public' }` in the file such as below, line after 19?
So that first it checke `mavenLocal` , followed by local nexus 
https://github.com/electrode-io/ColorPickerMiniApp/blob/master/android/build.gradle#L19

**Comment by jadolg** [comment]
In actually replaced all repositories with my local Nexus so I don't know why it's trying to download from other sources.

**Comment by jadolg** [comment]
So actually even when I changed the sources to only use my local nexus, other dependencies which ern installs are using these other repositories. This is forcing me to use other repositories which I have no access to because I live in Cuba. My nexus server is running on VPN but my laptop and my team's laptops are not. We are trying to reduce the internet usage to the minimum and this behavior of gradle is not helping.

**Comment by krunalsshah** [comment]
if you leave order as 
```
mavenLocal()
maven { url 'http://localhost:8081/nexus/content/groups/public' }
google()
jcenter()
```
I believe it must still look for all the sources. What EN dependencies are you specifically seeing being downloaded from other repositories?

**Comment by krunalsshah** [comment]
@jadolg We are closing the issue, please let us know if any of the above any other strategy worked for you.
