### ISSUE TITLE
Continuos deployment

### ISSUE THREAD

**Issue by anieblas** [electrode-io/electrode-native#717]
Hi electrode-native team:

After reading the [issue-716](https://github.com/electrode-io/electrode-native/issues/716) I would like to ask you what do you think is the best strategy for continuous deployments?

Thanks in advance.

**Comment by jadolg** [comment]
Do you have any docker image recommended for continuous integration of electrode-native projects?

**Comment by belemaire** [comment]
We don't have any Docker image yet available.
Moving this one to our backlog
