### ISSUE TITLE
Error opening iOS runner when using `ern run-ios`

### ISSUE THREAD

**Issue by amloelxer** [electrode-io/electrode-native#724]
Relevant info 
mac OS High Sierra 10.13.3 
Xcode Version 9.3 
Simulator running iOS 11.3 
Electrode-Native Version v0.17.0 

When running `ern run-ios`, Electrode Native cannot open the runner on the simulator. It builds the runner but fails to launch due to the error `ERR! simctl Error: simctl error running 'launch': An error was encountered processing the command (domain=FBSOpenApplicationServiceErrorDomain, code=1)`. This isn't a huge deal, as you can just quit that terminal process and manually open the runner on the phone, but it would be a nice fix. Attached are screenshots. Thanks! 
<img width="754" alt="screen shot 2018-04-26 at 11 30 15 am" src="https://user-images.githubusercontent.com/5010246/39315801-94d967de-4945-11e8-8535-43846caa8f47.png">
<img width="374" alt="screen shot 2018-04-26 at 11 22 56 am" src="https://user-images.githubusercontent.com/5010246/39315807-979baf72-4945-11e8-9178-dc5969afe60c.png">

**Comment by belemaire** [comment]
Moving this one to our backlog
