### ISSUE TITLE
Registered bridging API event handler called too many times

### ISSUE THREAD

**Issue by jomnius** [electrode-io/electrode-native#729]
I have miniapp, which is calling native app via generated bridging API created from swagger file. Everything works ok.

**PROBLEM**:
When I close the miniapp and open again, my API handler at native side is called twice (3x after I close and reopen the miniapp again etc.). My best guess is that iOS app should unregister event handlers - and there seems to be a related PR in Electrode Native bridge repo:

https://github.com/electrode-io/react-native-electrode-bridge/pull/34/files

I tried to catch "your" attention with some dummy PR comments, but no luck. Therefore I'm creating this dummy "bug report", requesting that maybe you could check that PR... Please?

**WHAT I ALREADY TRIED:**

- FAILED

I made sure that I register the event handlers only once, during the miniapp lifetime. That didn't help since the module that handles registering is deallocated, when miniapp closes, but the handlers just remain around as zombies. Therefore any local bookkeeping about previously registers handlers is lost at miniapp close.

When I reopen the miniapp, I register new listeners every time.

- FAILED

I sent an event at module init, before registering handler, hoping to detect whether event handler already exists. The handler is called "too late", so I register another one. Always.

- DID NOT TRY

I could add random time delay, wait for possible event handler to be called, but...

- DID NOT TRY

I could patch the Electrode Native code based on the open PR, but...

- DID NOT TRY

I could write a new native module to keep track of which handlers have been registered, but...

For our app this situation is pretty bad :(

**Comment by amloelxer** [comment]
@jomnius have they not been responsive to you on various repos? I too would like this fixed merged in for the bridge

**Comment by jomnius** [comment]
@amloelxer I can wait until next week, not that much hurry. Trying to get Google Analytics tracking done, got to love enhanced ecommerce... But after that I'll just patch bridging code locally.

**Comment by krunalsshah** [comment]
@jomnius did you try removing event listener before un mounting component?
& mounting it back on the subsequent launch? Please make sure to use the `react-native-electrode-bridge` > https://github.com/electrode-io/react-native-electrode-bridge/releases/tag/v1.5.11
https://github.com/electrode-io/react-native-erncolorpicker-api/blob/master/android/lib/src/main/java/com/colorpickerApi/ern/api/ColorPickerEvents.java#L37

**Comment by jomnius** [comment]
PR has been merged, this issue can be closed. Great many thanx!

**Comment by krunalsshah** [comment]
👍
