### ISSUE TITLE
Third party library integration

### ISSUE THREAD

**Issue by romanpozd-tg17** [electrode-io/electrode-native#730]
Hey,
Is it possible to integrate a third party library that need to be linked in native projects too?
Something like Auth0 lib.

**Comment by jomnius** [comment]
Yes in some cases, check what is manifest and it's plugins https://electrode.gitbooks.io/electrode-native/content/platform-parts/manifest.html#reusing-exiting-native-modules

**Comment by krunalsshah** [comment]
@romanpozd-tg17 yes it's possible to integrate 3rd party `npm` packages.
- Can you please let us know which package of `Auth0` lib you are considering?

**Comment by krunalsshah** [comment]
@romanpozd-tg17 please reopen the ticket if you have any specific question of update. 

`Can you please let us know which package of Auth0 lib you are considering?`
