### ISSUE TITLE
Unsupported plugin. No configuration found in manifest for react-native-shared-preferences

### ISSUE THREAD

**Issue by melissayu** [electrode-io/electrode-native#749]
Hi, 
I'm trying to add the [react-native-shared-preferences](https://www.npmjs.com/package/react-native-shared-preferences) package to my electrode miniapp but I'm seeing this Unsupported plugin error when I do `ern run-android`:

```
⠼ Generating Container[buildAndroidPluginsViews] Something went wrong: Error: Unsupported plugin. No configuration found in manifest for react-native-shared-preferences
[fillContainerHull] Something went wrong: Error: Unsupported plugin. No configuration found in manifest for react-native-shared-preferences
[generateContainer] Something went wrong. Aborting Container Generation
✖ Unsupported plugin. No configuration found in manifest for react-native-shared-preferences
runLocalContainerGen failed: Error: Unsupported plugin. No configuration found in manifest for react-native-shared-preferences
An error occurred: Unsupported plugin. No configuration found in manifest for react-native-shared-preferences
```

I have added `"react-native-shared-preferences@1.0.0"` to my manifest file and run `ern add react-native-shared-preferences`. I get the same error when trying to add the react-native-video package and doing the same steps of adding to manifest and running ern add. I have already tried `ern upgrade-miniapp` but still get the error. Am I missing a step or have something configured wrong?

**Comment by deepueg** [comment]
@melissayu Did you create a plugins entry as well for this package?

Please reference the doc here: https://electrode.gitbooks.io/electrode-native/content/platform-parts/manifest.html#reusing-exiting-native-modules

Also, please check the master manifest for samples.

**Comment by melissayu** [comment]
@deepueg Thanks for the quick response

Ah, no I hadn't create the plugins entry. Now I just added the directory and .java file and config.json. Now when I `ern run-android`, I get this new error which doesn't give me details on where exactly the issue is: 
```
⠏ Generating Container[fillContainerHull] Something went wrong: Error: cp: no such file or directory: src/main/java
[generateContainer] Something went wrong. Aborting Container Generation
✖ cp: no such file or directory: src/main/java
runLocalContainerGen failed: Error: cp: no such file or directory: src/main/java
An error occurred: cp: no such file or directory: src/main/java
```

**Comment by deepueg** [comment]
Please share your config.json or the repo if it's public. Looks like the module name for Android is `app`.  This is used by EN platform to look for the native code that needs to be copied inside the container.

**Comment by deepueg** [comment]
Just looked the github repo for shared preference. Please try the following.

```{
  "android": {
    "root": "",
    "moduleName": "android"
  }
}
```

**Comment by melissayu** [comment]
Thank you! That seemed to do the trick.
