### ISSUE TITLE
How to minimize size of released miniapp

### ISSUE THREAD

**Issue by jomnius** [electrode-io/electrode-native#759]
I have released our miniapp 6 times (non-public), the size was about 1.1M. When I tried to release it today, the size was going to be 3.6M. The upload (fortunately) failed for unknown reason.

Now I'm checking how to minimise the size of miniapp releasing. Doing this by adding folders and files into .npmignore file.

**QUESTION:**
Which files need to be released for miniapp to work?

From `npm publish` output I can see some random files e.g. 

> package.json, .babelrc, .buckconfig, .eslintrc.json, .flow-coverage-report.json, .flowconfig, .gitattributes, .prettierignore, .watchmanconfig, .yarnrc, app.json, rn-cli.config.js                                                                                                                                                                                 

How about releasing iOS ErnRunner project and related files? Those are not actually needed, when embedding miniapp into cauldron? It's there just for debugging and testing?

This is my current .npmignore file, with some of those already added:

> .container/
.jest/
.vscode/
coverage/
scripts/
__tests__/
config/
fastlane/
flow-coverage/
flow-typed/
ios/archive.xcarchive/
>
> Gemfile
Gemfile.lock
pom.xml
yarn.lock
>
> Jenkinsfile
.eslintrc.json
.flow-coverage-report.json
.flowconfig
.gitattributes
.prettierignore
.yarnrc
.zappr.yaml
>
> settings.gradle
build.gradle
**/.gradle/
**/.idea/
**/.settings/
**/gradle/
**/build/
*.iml
.classpath
gradlew
gradlew.bat
gradle.properties
local.properties
proguard-rules.pro

**Comment by deepueg** [comment]
@jomnius Can you please give more details on the release, are you releasing the app to the app store? releasing a binary to a repository ? or simply pushing the codebase to github? 
 
BTW, since the miniapp is mainly your javascript code and it generates an ios and android folder everytime the `ern run-android` or `ern run-ios` command is executed. However, once the folder is created the subsequent use of the command will not recreate it again unless it's deleted.  This behavior is to keep any change that developers have made to the native code intact.

**Comment by jomnius** [comment]
I did mention `npm publish` and I displayed contents of `.npmignore' file, so I was talking about how to minimize the size of miniapp published to NPM registry.

I never use `ern run-ios`, never got it working. There is an "iOS" folder with customised code, but that's used for ErnRunner app only, I now believe. Will try to ignore it, to minimize package size.

Yesterday I managed to publish the miniapp 2 times, guess I need to continue experimenting. Found out there was a reference in code to "config" folder, so had to remove it from .npmignore file. However that is not a generic rule, just our custom implementation detail.

**Comment by deepueg** [comment]
My bad, I misread it. 

You can ignore the `android` and `ios` folders as they are not used when a container is generated. I think that definitely saves some space.

**Comment by belemaire** [comment]
Yes, to add on top of @deepueg regarding `android` and `ios` folders.
These one (the runners) should be added to the git repo, especially in case they contain native modifications. In the ideal scenario, these projects should be the ones containing some code to make the MiniApp run in isolation, for experimenting, development, testing, so they might contain custom code modifications and therefore should be shared with the rest of the MiniApp development team.
That being said, these are totally useless when publishing the app to npm and should not be included in the published npm package.
When we create a MiniApp it seems like we are not creating a `.npmignore` file at the root of the MiniApp. Given that under the hood `ern create-miniapp` calls `react-native init` it makes sense as React Native apps are not really meant to be published to NPM whereas MiniApps might. 
So we should generate a proper .npmignore when calling `ern create-miniapp` which exclude `ios` and `android` directories. Let's also make sure that other files not needed to be part of the NPM package are also excluded (though `ios` and `android` directory represent the vast majority of the overall size).
Will keep this issue open until implementation is done.
Thanks for reporting @jomnius !
