### ISSUE TITLE
run-android fails for missing com.walmartlabs.ern:react-native:0.55.3

### ISSUE THREAD

**Issue by gmusick** [electrode-io/electrode-native#766]
Running through the Getting Started steps at https://electrode.gitbooks.io/electrode-native/getting-started/getting-started.html throws an error when I run step 3 of Creating the MovieList MiniApp:

```
An error occurred: Command failed: ./gradlew lib:uploadArchives

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':lib:releaseCompileClasspath'.
> Could not find com.walmartlabs.ern:react-native:0.55.3.
  Searched in the following locations:
      file:/Users/greg/Library/Android/sdk/extras/m2repository/com/walmartlabs/ern/react-native/0.55.3/react-native-0.55.3.pom
      file:/Users/greg/Library/Android/sdk/extras/m2repository/com/walmartlabs/ern/react-native/0.55.3/react-native-0.55.3.jar
      file:/Users/greg/Library/Android/sdk/extras/google/m2repository/com/walmartlabs/ern/react-native/0.55.3/react-native-0.55.3.pom
      file:/Users/greg/Library/Android/sdk/extras/google/m2repository/com/walmartlabs/ern/react-native/0.55.3/react-native-0.55.3.jar
      file:/Users/greg/Library/Android/sdk/extras/android/m2repository/com/walmartlabs/ern/react-native/0.55.3/react-native-0.55.3.pom
      file:/Users/greg/Library/Android/sdk/extras/android/m2repository/com/walmartlabs/ern/react-native/0.55.3/react-native-0.55.3.jar
      file:/Users/greg/.m2/repository/com/walmartlabs/ern/react-native/0.55.3/react-native-0.55.3.pom
      file:/Users/greg/.m2/repository/com/walmartlabs/ern/react-native/0.55.3/react-native-0.55.3.jar
      https://jcenter.bintray.com/com/walmartlabs/ern/react-native/0.55.3/react-native-0.55.3.pom
      https://jcenter.bintray.com/com/walmartlabs/ern/react-native/0.55.3/react-native-0.55.3.jar
      https://dl.google.com/dl/android/maven2/com/walmartlabs/ern/react-native/0.55.3/react-native-0.55.3.pom
      https://dl.google.com/dl/android/maven2/com/walmartlabs/ern/react-native/0.55.3/react-native-0.55.3.jar
      https://repo1.maven.org/maven2/com/walmartlabs/ern/react-native/0.55.3/react-native-0.55.3.pom
      https://repo1.maven.org/maven2/com/walmartlabs/ern/react-native/0.55.3/react-native-0.55.3.jar
      https://jitpack.io/com/walmartlabs/ern/react-native/0.55.3/react-native-0.55.3.pom
      https://jitpack.io/com/walmartlabs/ern/react-native/0.55.3/react-native-0.55.3.jar
  Required by:
      project :lib

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
```

Electrode-native version: v0.18.2 (but this also happens with v0.16.1 and v0.17.0). Any ideas?

Thanks

**Comment by krunalsshah** [comment]
@belemaire FYI
Yes we are looking into this issue.

**Comment by krunalsshah** [comment]
@gmusick As a workaround while we are fixing the issue 
You may download the files from https://dl.bintray.com/belemaire/react-native/com/walmartlabs/ern/react-native/0.55.3/

`cd` into  /Users/greg/Library/Android/sdk/extras/m2repository
create directories `walmartlabs/ern/react-native/0.55.3` & copy over the files downloaded from https://dl.bintray.com/belemaire/react-native/com/walmartlabs/ern/react-native/0.55.3/

**Comment by belemaire** [comment]
FYI to other users who might experience this issue.
Our artifact has been for some reason unpublished from JCenter artifactory without any given notice.
We have reached out to the JFrog team for a resolution.
Thanks for your patience.

**Comment by belemaire** [comment]
@gmusick 
JFrog team has resolved the issue, artifacts are now back in JCenter.
From now on, we will also publish this artifact to MavenCentral in addition to JCenter, so that in case one or the other is failing, an alternative repository is available.
Closing this issue now.

**Comment by belemaire** [comment]
Close

**Comment by krunalsshah** [comment]
The issue has been resolved. We have now published the artifact on mavenCentral & Jcenter.

**Comment by krunalsshah** [comment]
The issue has been resolved. We have now published the artifact on mavenCentral & Jcenter.

**Comment by krunalsshah** [comment]
The issue has been resolved. We have now published the artifact on mavenCentral & Jcenter.
