### ISSUE TITLE
ern regen-api deleted all but schema.json file

### ISSUE THREAD

**Issue by jomnius** [electrode-io/electrode-native#793]
I'm struggling to generate correct API files, so I was experimenting with the "version" command line parameter. As result all files in folder were deleted, except schema.json file.

Not sure, if this is a bug, so reporting just in case. At least I didn't expect this kind of results.

```bash
ern regen-api --skipVersion --bridgeVersion 1
```

I believe that at least package.json file should have remained, because "correct" command, i.e. without version, complained about missing package.json file. Before my failed experiment the normal command used to work more or less ok.

Command ern --version reports:
```bash
ern-local-cli : 0.18.2
electrode-native : 1.0.14
```

**Comment by krunalsshah** [comment]
@jomnius Not entirely related to the question posted above. Although the `--bridgeVersion` should be one of https://github.com/electrode-io/react-native-electrode-bridge/releases
Before investigating deeper can you please run the command with the correct `--bridgeVersion`, in any case, the platform must prompt if the bridge version is incorrect.

**Comment by jomnius** [comment]
Documentation wasn't clear about what values should be given to `--bridgeVersion`, so I used a random value. Version 1 was a good guess, I think :)

Running the command with recognized version number does not delete files. There are other problems, which are irrelevant to this issue.

**Comment by krunalsshah** [comment]
@jomnius Documentation is fixed. Can we please close the issue?
