### ISSUE TITLE
ern run-ios -d <descriptor> can't find cli.js

### ISSUE THREAD

**Issue by gmusick** [electrode-io/electrode-native#803]
Hello,

I'm trying to start up a container described by a local cauldron via:

`ern run-ios -d MyApp:ios:0.0.1`

on ern 0.19.0. However, I'm getting the following error when launching the packager:

```
module.js:549
    throw err;
    ^

Error: Cannot find module '/Users/me/.ern/containergen/out/ios/ElectrodeContainer/Libraries/ReactNative/local-cli/cli.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
Process terminated. Press <enter> to close the window
```

My `cauldron.json` looks like:

```
{
  "nativeApps": [
    {
      "name": "MyApp",
      "platforms": [
        {
          "name": "ios",
          "versions": [
            {
              "name": "0.0.1",
              "binary": null,
              "codePush": {},
              "container": {
                "jsApiImpls": [],
                "miniApps": [
                  "file:/path/to/my/miniapp"
                ],
                "nativeDeps": [
                  "react-native@0.55.3"
                ],
                "ernVersion": "0.19.0"
              },
              "isReleased": false,
              "nativeDeps": [],
              "yarnLocks": {
                "container": "b2db7fde2b98f78ffb10cb65e4f252fc9215be12"
              },
              "containerVersion": "1.0.0"
            }
          ],
          "config": {
            "containerGenerator": {
              "containerVersion": "1.0.0"
            }
          }
        }
      ]
    }
  ],
  "schemaVersion": "1.0.0"
}
```

I've also tried with a remote cauldron as well as ern 0.18.2 and get the same error. Any ideas what I'm doing wrong?

Thanks.

**Comment by belemaire** [comment]
@gmusick 
I think the error you are experiencing with the packager is a false negative.
This is actually not the packager being launched by Electrode Native but it's the packager that is launched by React Native itself during build of React iOS library (triggered by the build of the iOS Electrode Native Runner or any native iOS application that has a dependency on an Electrode Native Container). 
This packager being launched by React Native on iOS is not used at all with Electrode Native so you should just discard this error. We are actually working on removing this packager launch from [React project iOS build phase](https://github.com/facebook/react-native/blob/v0.55.4/React/React.xcodeproj/project.pbxproj#L4007-L4020) as it's not of use with Electrode Native (Electrode Native launches the packager on its own). 
As a coincidence, we are at the moment working on a Electrode Native manifest update to remove this `start packager` build phase from the react pbxproj as its a bummer and create confusion with users. Should be done today.

Please note that if you use `run-ios` / `run-android` with a descriptor from Cauldron, it won't launch a packager (same if you use these commands with multiple MiniApps). This is unfortunately not really documented. We might work soon on starting the packager for multiple miniapps as we have support for that feat in another command (`ern start`).

**Comment by belemaire** [comment]
Been closed by 
https://github.com/electrode-io/electrode-native-manifest/commit/1cf831c9eca3e7abe2d42c6f1aeb541fde06de97

From now on, any Container being generated with react-native > 0.49 will not trigger packager being launched during build of React.xcodeproj.

**Comment by gmusick** [comment]
👍
