### ISSUE TITLE
Manifest should support iOS directive to declare target dependencies.

### ISSUE THREAD

**Issue by cihancimen** [electrode-io/electrode-native#811]
Similar to adding a linked library, `addProject` directive should support adding target dependencies.
Following directive should add a target dependency, without changing `Link Binary with Libraries` build phase.
```
"addProject": [
 { 
          "path": "../../../../../Modules/WalmartIOSShared/WalmartIOSShared.xcodeproj", 
          "group": "TargetDependencies", 
          "frameworks": [ { "name": "WalmartIOSShared.framework", "target": "WalmartIOSShared", "productReference": "07C5A03F1C472F4600157A12" } ] 
        }
]
```

**Comment by belemaire** [comment]
@cihancimen 
Just released v0.20.0 which includes the necessary in https://github.com/electrode-io/electrode-native/pull/813. Was a bit trickier than planned but its working. Got manifest changes ready, will follow up with you and @gmbharath12 tomorrow.
