### ISSUE TITLE
Resource compilation issue in react-native plugin

### ISSUE THREAD

**Issue by dbellizzi** [electrode-io/electrode-native#832]
I'm trying to include [react-native-image-picker](https://github.com/react-community/react-native-image-picker), which is not supported by the global manifest.  I've created a plugin in my local manifest that looks like this:

```java
package com.walmartlabs.ern.container.plugins;

import android.app.Application;
import android.support.annotation.NonNull;
import android.support.annotation.Nullable;

import com.facebook.react.ReactPackage;

import com.imagepicker.ImagePickerPackage;

public class ImagePickerPlugin {

  public ReactPackage hook(@NonNull Application application,
                           ReactPluginConfig config) {
    ImagePicker imagePicker = new ImagePickerPackage();
    return imagePicker;
  }
}
```
and a config file that looks like this:
```json
{
  "android": {
    "root": "",
    "moduleName": "android",
    "dependencies": [
      "com.android.tools.build:gradle:2.2.+"
    ],
    "permissions": [
      "android.permission.CAMERA",
      "android.permission.WRITE_EXTERNAL_STORAGE"
    ]
  }
}
```

When running `ern-android`, I get a compile error:
```
✔ Generating Container
/Users/dbellizzi/.ern/container-publishers-cache /private/var/folders/41/04pdc7vx74d_q5m240cnp26m0000gn/T/tmp-76695vQg95g1DUaIi
/private/var/folders/41/04pdc7vx74d_q5m240cnp26m0000gn/T/tmp-76695vQg95g1DUaIi
[=== Starting build and publication ===]
/private/var/folders/41/04pdc7vx74d_q5m240cnp26m0000gn/T/tmp-76695RpcG6ovnpBpf /private/var/folders/41/04pdc7vx74d_q5m240cnp26m0000gn/T/tmp-76695vQg95g1DUaIi
/private/var/folders/41/04pdc7vx74d_q5m240cnp26m0000gn/T/tmp-76695vQg95g1DUaIi
An error occurred: Command failed: ./gradlew lib:uploadArchives
/private/var/folders/41/04pdc7vx74d_q5m240cnp26m0000gn/T/tmp-76695RpcG6ovnpBpf/lib/src/main/java/com/imagepicker/utils/UI.java:13: error: cannot find symbol
import com.imagepicker.R;
                      ^
  symbol:   class R
  location: package com.imagepicker
/private/var/folders/41/04pdc7vx74d_q5m240cnp26m0000gn/T/tmp-76695RpcG6ovnpBpf/lib/src/main/java/com/imagepicker/permissions/PermissionUtils.java:12: error: cannot find symbol
import com.imagepicker.R;
                      ^
  symbol:   class R
  location: package com.imagepicker
/private/var/folders/41/04pdc7vx74d_q5m240cnp26m0000gn/T/tmp-76695RpcG6ovnpBpf/lib/src/main/java/com/imagepicker/utils/UI.java:39: error: package R does not exist
                R.layout.list_item,
                 ^
/private/var/folders/41/04pdc7vx74d_q5m240cnp26m0000gn/T/tmp-76695RpcG6ovnpBpf/lib/src/main/java/com/imagepicker/ImagePickerPackage.java:16: error: package R does not exist
  public static final int DEFAULT_EXPLAINING_PERMISSION_DIALIOG_THEME = R.style.DefaultExplainingPermissionsTheme;
                                                                         ^
Note: /private/var/folders/41/04pdc7vx74d_q5m240cnp26m0000gn/T/tmp-76695RpcG6ovnpBpf/lib/src/main/java/com/walmartlabs/electrode/reactnative/bridge/util/BridgeArguments.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
4 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':lib:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
```

It looks like the resource XML files are not being compiled correctly for the plugin to reference.  You can see that they are present here: https://github.com/react-community/react-native-image-picker/tree/develop/android/src/main/res

Thanks for any help you can provide.

**Comment by dbellizzi** [comment]
I *think*, that if I rewrite the import statements in the npm module from `com.imagepicker.R` to `com.walmartlabs.ern.container.R` that this will work.  I'm working on trying that now.

**Comment by dbellizzi** [comment]
So I've found two issues:
First, the command 
`/Users/dbellizzi/.ern/versions/0.20.0/node_modules/ern-core/node_modules/.bin/react-native bundle --entry-file=index.android.js --dev=false --platform=android --bundle-output=/Users/dbellizzi/.ern/containergen/out/android/lib/src/main/assets/index.android.bundle --assets-dest=/Users/dbellizzi/.ern/containergen/out/android/lib/src/main/res` 
isn't actually copying over the resource XML files from the plugin.  I've verified that they are packaged in the npm module.

Second, if I manually copy them over during container generation, I get the above error until I rewrite the source to reference `com.walmartlabs.ern.container.R` instead of `com.imagepicker.R`

**Comment by krunalsshah** [comment]
Added the initial support for ` react-native-image-picker`
 https://github.com/electrode-io/electrode-native-manifest/pull/47

**Comment by joshhanna** [comment]
@dbellizzi, how'd you manage to work through this?

I'm using the plugin in the main manifest, and still getting the same compilation error you mentioned, even on an otherwise untouched `ern create-miniapp`ed project.

**Comment by dbellizzi** [comment]
Unfortunately, we never did and stopped using react-native-image-picker, and I haven't tried to use it recently
