### ISSUE TITLE
Is it possible to run MiniApp against a native application with live reload?

### ISSUE THREAD

**Issue by byronmwong** [electrode-io/electrode-native#846]
We want to test out integrations over the native bridge (e.g., launching a native activity). Currently, this involves:

* building and publishing a container via `ern create-container`
* grabbing the published container in the native app's project
* rebuilding the native project

If we discover an issue with the integration and want to iterate on the code, any change involves repeating all the steps above, which makes for a slow feedback loop.

It'd be nice to be able to mount a container into the native app that fetches JS from the RN Bundler so we can iterate with live reload. It seems possible because that's what `ern run-android` is doing behind the scenes, but with the small Runner app instead of our own native app. Is there a way to make this happen?

Thanks!

**Comment by byronmwong** [comment]
Made some progress on this:

If you run `ern run-android` for a single MiniApp, a container gets built and published. You'll see output like:

```
[=== Completed build and publication of the Container ===]
[Publication url : file:///Users/byron/.m2/repository]
[Artifact: com.walmartlabs.ern:runner-ern-container:1.0.0 ]
```

Then, in the native app's `app/build.gradle`, use the generated container

```
implementation('com.walmartlabs.ern:runner-ern-container:1.0.0')
```

And make sure to set dev mode on:

```
new ElectrodeReactContainer.Config().isReactNativeDeveloperSupport(true)
```

With all that, you can get hot reload in the native host.

**Comment by krunalsshah** [comment]
@byronmwong Yes you are going on the right track.

https://native.electrode.io/reference/index-3
https://facebook.github.io/react-native/docs/debugging.html

Sorry for the delay, if you are still stuck please let us know and re open the ticket.

**Comment by adiwon9555** [comment]
This is the log after running ern run-android, 
` A React Native Packager is already running in a different process
✔ Generating Composite locally 25s
  ✔ Generating Composite 24s
    ✔ Cleaning up existing composite directory 0s
    ✔ Adding extra packages to the composite 15s
    ✔ Syncing git@bitbucket.org:vedantu/vedantu-electrode-manifest.git Manifest 6s
    ✔ Syncing https://github.com/electrode-io/electrode-native-manifest.git Manifest 1s
⚠ A React Native Packager is already running in a different process
✔ Generating Composite locally 25s
  ✔ Generating Composite 24s
    ✔ Cleaning up existing composite directory 0s
    ✔ Adding extra packages to the composite 15s
    ✔ Syncing git@bitbucket.org:vedantu/vedantu-electrode-manifest.git Manifest 6s
    ✔ Syncing https://github.com/electrode-io/electrode-native-manifest.git Manifest 1s
✔ Generating Container locally 26s
  ✔ Generating Container 26s
    ✔ Resolving native dependencies 0s
    ✔ Preparing Native Dependencies Injection 0s
    ✔ Adding Native Dependencies Hooks 0s
    ✔ Setting Android tools and libraries versions 0s
    ✔ Injecting Native Dependencies 0s
    ✔ Injecting JavaScript engine [JavaScriptCore] 1s
    ✔ Bundling MiniApps 24s
      ✔ Running Metro Bundler 24s
    ✔ Adding Electrode Native Metadata File 0s
✔ Regenerating android Runner Configuration 0s
✔ Building and installing application 13s
✔ Launching Android Application 0s
`
@bywo can u please explain what to do next to get hot reload?

**Comment by bywo** [comment]
sorry, I haven't used electrode-native in a long time, so I don't remember.
