### ISSUE TITLE
runLocalContainerGen failed: Error: The following plugins are not using compatible versions :   react-native

### ISSUE THREAD

**Issue by cohen72** [electrode-io/electrode-native#858]
when running the following command:

`ern run-ios --miniapps moviedetailsminiapp@0.0.20 --mainMiniAppName MovieListMiniApp`

The following error is produced:
```
runLocalContainerGen failed: Error: The following plugins are not using compatible versions :

        react-native
An error occurred: The following plugins are not using compatible versions :

        react-native
```

![image](https://user-images.githubusercontent.com/1394233/42817882-16d009dc-89d8-11e8-9c72-6d37dcc15833.png)

react-native version 0.56.0
react-native-cli: 2.0.1

**Comment by krunalsshah** [comment]
@cohen72 currently we are targeting  `react-native version 0.55.4` in the open source manifest
https://github.com/electrode-io/electrode-native-manifest/blob/master/manifest.json#L384

Can you please try ? Please reopen the issue if you are facing errors.
