### ISSUE TITLE
Cannot read propert '1' of null Error

### ISSUE THREAD

**Issue by aminkh17** [electrode-io/electrode-native#943]
I have setup electrode on my machine and try to execute ern run-android but I am getting the error below 

× runLocalContainerGen failed: TypeError: Cannot read property '1' of null
× An error occurred: Cannot read property '1' of null

My machine is Windows 10 and I can see the following error exactly before popup command closing.

Loading dependency graph...
"port" argument must be >= 0 and <= 65536

**Comment by belemaire** [comment]
Thanks for reporting and sorry for belated answer.
We made various Windows fixes in recent PR https://github.com/electrode-io/electrode-native/pull/961
This include a fix for the problem you are fixing. 
These fixes will be released in upcoming `v0.25.0` version of Electrode Native, to be released over the week-end.
Will close this issue now, feel free to reopen after the week-end in case you're still facing the issue with new version of Electrode Native (but should be good).
