### ISSUE TITLE
Change the App name

### ISSUE THREAD

**Issue by amink-c** [electrode-io/electrode-native#959]
Looks like every time ern run-ios is trying to create another app with name of ErnRunner even there is and existence app inside ios folder.

How can I tell ern to use the previous existence app?

The error is 
An error occurred: cp: copyFileSync: could not write to dest file (code=ENOENT):/MyApp/ios/ErnRunner/RunnerConfig.m

Which is my app name is not ErnRunner

**Comment by gmbharath12** [comment]
Please install ern version `0.27.0` and test it. To install 0.27.0 use the command: `ern platform use 0.27.0`

Use xcode 10.1

**Comment by belemaire** [comment]
Closing this issue, feel free to reopen if needed.
