### ISSUE TITLE
ern run-android error

### ISSUE THREAD

**Issue by alvarocasta** [electrode-io/electrode-native#971]
Hi,

Since the last updates I am not able to run "ern run-android" as I receive the next error:

```
✔ Adding Electrode Native Metadata File 0s
An error occurred: Command failed: ./gradlew lib:uploadArchives
/private/var/folders/yt/pq5y2d5x5wjb9ywpzp3zkb9r0000gn/T/tmp-31787nIbI783bsV0Q/lib/src/main/java/com/walmartlabs/ern/container/miniapps/ElectrodeMiniAppActivity.java:16: 
error: ElectrodeMiniAppActivity is already defined in this compilation unit

import com.walmartlabs.ern.container.ElectrodeMiniAppActivity;
/private/var/folders/yt/pq5y2d5x5wjb9ywpzp3zkb9r0000gn/T/tmp-31787nIbI783bsV0Q/lib/src/main/java/com/walmartlabs/ern/container/miniapps/ElectrodeMiniAppActivity.java:18: 
error: cyclic inheritance involving ElectrodeMiniAppActivity
public class ElectrodeMiniAppActivity extends ElectrodeMiniAppActivity {

```
Running the same command with sudo, I get the error:

```
✔ Adding Electrode Native Metadata File 0s
An error occurred: Command failed: ./gradlew lib:uploadArchives
FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring project ':lib'.
 > SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.
```

What is weird as I have defined the variable ANDROID_HOME.

I have tried without success:
* reinstall electrode globally: `npm install -g electrode-native`
* clean cache: `rm -rf ~/.ern/` and `rm -rf ~/.rncache`
* create from scratch a new project `ern create-miniapp projectName`
* trying the same on a second computer (same errors)

I am using Node v8.12.0 and Ern v0.25.1

**Comment by alvarocasta** [comment]
issue seems fixed. Not sure which step fixed it, but it could be related to: `rm -rf ~/.gradle/caches/`

**Comment by alvarocasta** [comment]
In a funny way I just realised what the problem was. The name of the project I used was "ElectrodeMiniApp". 
`ern create-miniapp ElectrodeMiniApp`
Somehow this gets mixed up on the Android project compilation.

**Comment by krunalsshah** [comment]
Thanks for reporting the issue, it's certainly funny that `ElectrodeMiniApp` extends `ElectrodeMiniApp` :) Closing the issue.
