### ISSUE TITLE
Use of undeclared identifier 'NavigationAPI' iOS runner

### ISSUE THREAD

**Issue by nelsonchen5** [electrode-io/electrode-native#976]
I am going through the tutorial "Building a Movie Application API" and I reach the part where I have to implement the Navigation API in the native application. However; in XCode, I see this error message:
"Use of undeclared identifier 'NavigationAPI'

![image](https://user-images.githubusercontent.com/31781643/48382863-ffbfa500-e697-11e8-95a8-ddd50fa48de6.png)

I then run 

`ern run-ios --miniapps moviedetailsminiapp@0.0.22 --mainMiniAppName MovieListMiniApp`

and I receive the error:

![image](https://user-images.githubusercontent.com/31781643/48382924-6b097700-e698-11e8-8b30-86298748987f.png)

**Comment by nelsonchen5** [comment]
I also just tried pulling the example project from:

https://github.com/electrode-io/MovieListMiniApp#run-the-app-with-moviedetailsminiapp

and it gives me similar errors

![image](https://user-images.githubusercontent.com/31781643/48519509-037f3300-e822-11e8-8b68-ea430c64b148.png)


Mind checking out what the issue is?

**Comment by davidgovea** [comment]
What version of XCode are you using? I'm seeing the same on 10.1

**Comment by nelsonchen5** [comment]
I am also on XCode 10.1

**Comment by belemaire** [comment]
Sorry for not giving feedback in time on this issue.
Closing it now, feel free to reopen if needed.
